//! Renderer-owned resources shared by full-scene and auxiliary rendering.
use super::*;

pub struct Renderer {
    pub(super) pipeline: wgpu::RenderPipeline,
    pub(super) world_pipeline: wgpu::RenderPipeline,
    pub(super) world_stroke_pipeline: wgpu::RenderPipeline,
    pub(super) terminal_graphics: terminal_graphics::TerminalGraphicsRenderer,
    pub(super) uniform_bind_group: wgpu::BindGroup,
    pub(super) uniform_buffer: wgpu::Buffer,
    pub(super) scene_bind_group: wgpu::BindGroup,
    pub(super) scene_bind_group_layout: wgpu::BindGroupLayout,
    pub(super) surface_world_bundles: Vec<gpu_surface_pass::CachedSurfaceBundle>,
    pub(super) surface_scene_uniforms: Vec<(wgpu::Buffer, wgpu::BindGroup)>,
    pub(super) surface_grid_vertex_buffer: Option<wgpu::Buffer>,
    pub(super) surface_grid_vertex_capacity: usize,
    pub(super) schematic_scene_bind_group: wgpu::BindGroup,
    pub(super) schematic_world_vertex_buffer: Option<wgpu::Buffer>,
    pub(super) schematic_world_vertex_capacity: usize,
    pub(super) schematic_world_vertex_source: Option<std::sync::Arc<[Vertex]>>,
    pub(super) schematic_world_stroke_buffer: Option<wgpu::Buffer>,
    pub(super) schematic_world_stroke_capacity: usize,
    pub(super) schematic_world_stroke_source_ptr: usize,
    pub(super) schematic_world_stroke_source_len: usize,
    pub(super) schematic_underlay_vertex_buffer: Option<wgpu::Buffer>,
    pub(super) schematic_underlay_vertex_capacity: usize,
    pub(super) schematic_overlay_vertex_buffer: Option<wgpu::Buffer>,
    pub(super) schematic_overlay_vertex_capacity: usize,
    pub(super) font_system: FontSystem,
    pub(super) swash_cache: SwashCache,
    pub(super) viewport: Viewport,
    pub(super) atlas: TextAtlas,
    pub(super) text_renderer: TextRenderer,
    pub(super) menu_overlay_text_renderer: TextRenderer,
    pub(super) text_buffer_cache: Vec<CachedTextBuffer>,
    pub(super) text_buffer_frame: u64,
    pub(super) last_text_prepare_signature: Option<TextPrepareSignature>,
    pub(super) panel_vertex_buffer: Option<wgpu::Buffer>,
    pub(super) panel_vertex_capacity: usize,
    pub(super) viewport_underlay_vertex_buffer: Option<wgpu::Buffer>,
    pub(super) viewport_underlay_vertex_capacity: usize,
    pub(super) viewport_overlay_vertex_buffer: Option<wgpu::Buffer>,
    pub(super) viewport_overlay_vertex_capacity: usize,
    pub(super) board_interaction_vertex_buffer: Option<wgpu::Buffer>,
    pub(super) board_interaction_vertex_capacity: usize,
    pub(super) console_gpu: gpu_console::ConsoleGpuResources,
    pub(super) menu_overlay_vertex_buffer: Option<wgpu::Buffer>,
    pub(super) menu_overlay_vertex_capacity: usize,
    pub(super) world_vertex_buffer: Option<wgpu::Buffer>,
    pub(super) world_vertex_capacity: usize,
    pub(super) world_vertex_source: Option<std::sync::Arc<[Vertex]>>,
    pub(super) world_stroke_buffer: Option<wgpu::Buffer>,
    pub(super) world_stroke_capacity: usize,
    pub(super) world_stroke_source_ptr: usize,
    pub(super) world_stroke_source_len: usize,
    pub(super) msaa_view: Option<wgpu::TextureView>,
    pub(super) msaa_size: (u32, u32),
    pub(super) msaa_format: wgpu::TextureFormat,
    pub(super) msaa_samples: u32,
    pub(super) measurements: Option<gpu_measurements::GpuMeasurements>,
}
