//! Renderer-owned resources shared by full-scene and auxiliary rendering.
use super::*;

pub struct Renderer {
    pub(super) schematic_world_strokes_gpu:
        gpu_data::retained_buffer::RetainedBuffer<WorldStrokeInstance>,
    pub(super) schematic_world_vertices_gpu: gpu_data::retained_buffer::RetainedBuffer<Vertex>,
    pub(super) world_strokes_gpu: gpu_data::retained_buffer::RetainedBuffer<WorldStrokeInstance>,
    pub(super) world_vertices_gpu: gpu_data::retained_buffer::RetainedBuffer<Vertex>,
    pub(super) pipeline: wgpu::RenderPipeline,
    pub(super) world_pipeline: wgpu::RenderPipeline,
    pub(super) world_stroke_pipeline: wgpu::RenderPipeline,
    pub(super) terminal_graphics: terminal_graphics::TerminalGraphicsRenderer,
    pub(super) uniform_bind_group: wgpu::BindGroup,
    pub(super) uniform_buffer: wgpu::Buffer,
    pub(super) scene_bind_group: wgpu::BindGroup,
    pub(super) scene_bind_group_layout: wgpu::BindGroupLayout,
    pub(super) surface_world_bundles: Vec<gpu_surface_pass::CachedSurfaceBundle>,
    pub(super) surface_scene_uniforms: Vec<(wgpu::Buffer, wgpu::BindGroup)>,
    pub(super) surface_grid_gpu: gpu_data::screen_buffer::ScreenBuffer,
    pub(super) schematic_scene_bind_group: wgpu::BindGroup,
    pub(super) schematic_underlay_gpu: gpu_data::screen_buffer::ScreenBuffer,
    pub(super) schematic_overlay_gpu: gpu_data::screen_buffer::ScreenBuffer,
    pub(super) font_system: FontSystem,
    pub(super) swash_cache: SwashCache,
    pub(super) viewport: Viewport,
    pub(super) atlas: TextAtlas,
    pub(super) text_renderer: TextRenderer,
    pub(super) menu_overlay_text_renderer: TextRenderer,
    pub(super) text_buffers: text_buffer_cache::TextBufferCache,
    pub(super) last_text_prepare_signature: Option<TextPrepareSignature>,
    pub(super) panel_gpu: gpu_data::screen_buffer::ScreenBuffer,
    pub(super) viewport_underlay_gpu: gpu_data::screen_buffer::ScreenBuffer,
    pub(super) viewport_overlay_gpu: gpu_data::screen_buffer::ScreenBuffer,
    pub(super) board_interaction_gpu: gpu_data::screen_buffer::ScreenBuffer,
    pub(super) console_gpu: gpu_console::ConsoleGpuResources,
    pub(super) menu_overlay_gpu: gpu_data::screen_buffer::ScreenBuffer,
    pub(super) surface_attachments: gpu_surface::SurfaceAttachments,
    pub(super) msaa_format: wgpu::TextureFormat,
    pub(super) msaa_samples: u32,
    pub(super) measurements: Option<gpu_measurements::GpuMeasurements>,
}
