//! The `datum.proposal` terminal verb family (20 verbs), transcribed from the
//! hand-written MCP catalog (`tools_catalog_proposals.py` /
//! `tools_catalog_output_jobs.py` schemas via `tools_catalog_datum.py`
//! aliases), the Python bridge argv builders (`server_runtime.py` /
//! `server_runtime_proposals.py`), and cross-checked against the clap
//! definitions in `crates/cli/src/cli_args_proposals.rs` /
//! `cli_args_proposal_library.rs` / `cli_args_project_proposals.rs`.
//!
//! Only the verbs advertised in the GUI terminal command catalog are
//! registered here; the rest of the `datum.proposal` family migrates later.
//!
//! Entries MUST stay sorted by id (asserted by lib tests).

use crate::{ArgvToken, Dispatch, ParamSpec, ParamType, VerbSpec, VerbStatus, WriteSurface};

const PROPOSAL_METADATA_WRITE: WriteSurface = WriteSurface {
    class: "proposal_metadata_write",
    evidence: "writes only persisted proposal metadata for later review; does not mutate design shards",
};

const PROPOSAL_REVIEW_STATE_WRITE: WriteSurface = WriteSurface {
    class: "proposal_review_state_write",
    evidence: "updates persisted proposal review state without applying design mutations",
};

const PROPOSAL_GATEWAY_APPLY: WriteSurface = WriteSurface {
    class: "proposal_gateway_apply",
    evidence: "applies an accepted proposal through the generic proposal journal gateway",
};

const PATH: ParamSpec = ParamSpec {
    name: "path",
    ty: ParamType::Str,
    required: true,
    doc: "Project root directory",
    default_json: None,
};

const PROPOSAL_TARGET: ParamSpec = ParamSpec {
    name: "proposal",
    ty: ParamType::Uuid,
    required: true,
    doc: "Persisted proposal UUID",
    default_json: None,
};

const PROPOSAL_ID: ParamSpec = ParamSpec {
    name: "proposal",
    ty: ParamType::Uuid,
    required: false,
    doc: "Optional stable proposal UUID",
    default_json: None,
};

const RATIONALE: ParamSpec = ParamSpec {
    name: "rationale",
    ty: ParamType::Str,
    required: false,
    doc: "Proposal review rationale",
    default_json: None,
};

const PROPOSAL_ID_ARGV: ArgvToken = ArgvToken::Flag { flag: "--proposal", param: "proposal" };
const RATIONALE_ARGV: ArgvToken = ArgvToken::Flag { flag: "--rationale", param: "rationale" };

pub(crate) static VERBS: &[VerbSpec] = &[
    VerbSpec {
        id: "datum.proposal.accept_apply",
        summary: "Accept one draft native-project proposal and apply it through the generic proposal gateway.",
        status: VerbStatus::Public,
        replacements: &[],
        retirement: None,
        dispatch: Dispatch::Cli {
            method: "accept_apply_proposal",
            argv: &[
                ArgvToken::Lit("proposal"),
                ArgvToken::Lit("accept-apply"),
                ArgvToken::Param("path"),
                PROPOSAL_ID_ARGV,
            ],
        },
        params: &[PATH, PROPOSAL_TARGET],
        schema_json_override: None,
        write_surface: Some(PROPOSAL_GATEWAY_APPLY),
        terminal: true,
        terminal_optional_params: &[],
        terminal_argv_override: None,
    },
    VerbSpec {
        id: "datum.proposal.apply",
        summary: "Apply one accepted persisted native-project proposal through the generic proposal gateway.",
        status: VerbStatus::Public,
        replacements: &[],
        retirement: None,
        dispatch: Dispatch::Cli {
            method: "apply_proposal",
            argv: &[
                ArgvToken::Lit("proposal"),
                ArgvToken::Lit("apply"),
                ArgvToken::Param("path"),
                PROPOSAL_ID_ARGV,
            ],
        },
        params: &[PATH, PROPOSAL_TARGET],
        schema_json_override: None,
        write_surface: Some(PROPOSAL_GATEWAY_APPLY),
        terminal: true,
        terminal_optional_params: &[],
        terminal_argv_override: None,
    },
    VerbSpec {
        id: "datum.proposal.create_manufacturing_plan",
        summary: "Create a draft proposal for a ManufacturingPlan creation without mutating manufacturing plan shards.",
        status: VerbStatus::Public,
        replacements: &[],
        retirement: None,
        dispatch: Dispatch::Cli {
            method: "create_manufacturing_plan_proposal",
            argv: &[
                ArgvToken::Lit("proposal"),
                ArgvToken::Lit("create-manufacturing-plan"),
                ArgvToken::Param("path"),
                ArgvToken::Flag { flag: "--prefix", param: "prefix" },
                ArgvToken::Flag { flag: "--name", param: "name" },
                ArgvToken::Flag { flag: "--variant", param: "variant" },
                ArgvToken::Flag { flag: "--panel-projection", param: "panel_projection" },
                PROPOSAL_ID_ARGV,
                RATIONALE_ARGV,
            ],
        },
        params: &[
            PATH,
            ParamSpec {
                name: "prefix",
                ty: ParamType::Str,
                required: true,
                doc: "Deterministic manufacturing artifact filename prefix",
                default_json: None,
            },
            ParamSpec {
                name: "name",
                ty: ParamType::Str,
                required: false,
                doc: "Human-readable manufacturing plan name",
                default_json: None,
            },
            ParamSpec {
                name: "variant",
                ty: ParamType::Uuid,
                required: false,
                doc: "Optional variant UUID this plan targets",
                default_json: None,
            },
            ParamSpec {
                name: "panel_projection",
                ty: ParamType::Uuid,
                required: false,
                doc: "Optional panel projection UUID this plan targets instead of the board",
                default_json: None,
            },
            PROPOSAL_ID,
            RATIONALE,
        ],
        schema_json_override: None,
        write_surface: Some(PROPOSAL_METADATA_WRITE),
        terminal: true,
        terminal_optional_params: &[],
        terminal_argv_override: None,
    },
    VerbSpec {
        id: "datum.proposal.create_output_job",
        summary: "Create a draft proposal for an OutputJob creation without mutating the OutputJob shard.",
        status: VerbStatus::Public,
        replacements: &[],
        retirement: None,
        dispatch: Dispatch::Cli {
            method: "create_output_job_proposal",
            argv: &[
                ArgvToken::Lit("proposal"),
                ArgvToken::Lit("create-output-job"),
                ArgvToken::Param("path"),
                ArgvToken::Flag { flag: "--prefix", param: "prefix" },
                ArgvToken::Flag { flag: "--include", param: "include" },
                ArgvToken::Flag { flag: "--output-dir", param: "output_dir" },
                ArgvToken::Flag { flag: "--name", param: "name" },
                ArgvToken::Flag { flag: "--manufacturing-plan", param: "manufacturing_plan" },
                ArgvToken::Flag { flag: "--variant", param: "variant" },
                PROPOSAL_ID_ARGV,
                RATIONALE_ARGV,
            ],
        },
        params: &[
            PATH,
            ParamSpec {
                name: "prefix",
                ty: ParamType::Str,
                required: true,
                doc: "Deterministic output prefix this job will generate",
                default_json: None,
            },
            ParamSpec {
                name: "include",
                ty: ParamType::Str,
                required: true,
                doc: "Artifact include scopes: comma-separated gerber-set, manufacturing-set, bom, pnp, drill, or all",
                default_json: None,
            },
            ParamSpec {
                name: "name",
                ty: ParamType::Str,
                required: false,
                doc: "Human-readable output job name",
                default_json: None,
            },
            ParamSpec {
                name: "manufacturing_plan",
                ty: ParamType::Uuid,
                required: false,
                doc: "Manufacturing plan UUID this output job executes",
                default_json: None,
            },
            ParamSpec {
                name: "output_dir",
                ty: ParamType::Str,
                required: false,
                doc: "Preferred output directory for generated artifacts",
                default_json: None,
            },
            PROPOSAL_ID,
            RATIONALE,
            ParamSpec {
                name: "variant",
                ty: ParamType::Uuid,
                required: false,
                doc: "Variant overlay UUID this output job targets",
                default_json: None,
            },
        ],
        schema_json_override: None,
        write_surface: Some(PROPOSAL_METADATA_WRITE),
        terminal: true,
        terminal_optional_params: &[],
        terminal_argv_override: None,
    },
    VerbSpec {
        id: "datum.proposal.create_panel_projection",
        summary: "Create a draft proposal for a PanelProjection creation without mutating panel shards.",
        status: VerbStatus::Public,
        replacements: &[],
        retirement: None,
        dispatch: Dispatch::Cli {
            method: "create_panel_projection_proposal",
            argv: &[
                ArgvToken::Lit("proposal"),
                ArgvToken::Lit("create-panel-projection"),
                ArgvToken::Param("path"),
                ArgvToken::Flag { flag: "--key", param: "key" },
                ArgvToken::Flag { flag: "--name", param: "name" },
                ArgvToken::Flag { flag: "--board", param: "board" },
                ArgvToken::Flag { flag: "--x-nm", param: "x_nm" },
                ArgvToken::Flag { flag: "--y-nm", param: "y_nm" },
                ArgvToken::Flag { flag: "--rotation-deg", param: "rotation_deg" },
                PROPOSAL_ID_ARGV,
                RATIONALE_ARGV,
            ],
        },
        params: &[
            PATH,
            ParamSpec {
                name: "key",
                ty: ParamType::Str,
                required: true,
                doc: "Deterministic panel key",
                default_json: None,
            },
            ParamSpec {
                name: "name",
                ty: ParamType::Str,
                required: false,
                doc: "Human-readable panel projection name",
                default_json: None,
            },
            ParamSpec {
                name: "board",
                ty: ParamType::Uuid,
                required: false,
                doc: "Optional board UUID for the first panel instance; defaults to current board",
                default_json: None,
            },
            ParamSpec {
                name: "x_nm",
                ty: ParamType::Int,
                required: false,
                doc: "First board instance X offset in nanometers",
                default_json: None,
            },
            ParamSpec {
                name: "y_nm",
                ty: ParamType::Int,
                required: false,
                doc: "First board instance Y offset in nanometers",
                default_json: None,
            },
            ParamSpec {
                name: "rotation_deg",
                ty: ParamType::Int,
                required: false,
                doc: "First board instance rotation in degrees",
                default_json: None,
            },
            PROPOSAL_ID,
            RATIONALE,
        ],
        schema_json_override: None,
        write_surface: Some(PROPOSAL_METADATA_WRITE),
        terminal: true,
        terminal_optional_params: &[],
        terminal_argv_override: None,
    },
    VerbSpec {
        id: "datum.proposal.create_pool_pin_pad_map",
        summary: "Create a non-mutating draft proposal to author one first-class native pool PinPadMap.",
        status: VerbStatus::Public,
        replacements: &[],
        retirement: None,
        dispatch: Dispatch::Cli {
            method: "create_pool_pin_pad_map_proposal",
            argv: &[
                ArgvToken::Lit("proposal"),
                ArgvToken::Lit("create-pool-pin-pad-map"),
                ArgvToken::Param("path"),
                ArgvToken::Flag { flag: "--pool", param: "pool" },
                ArgvToken::Flag { flag: "--map", param: "map" },
                ArgvToken::Flag { flag: "--part", param: "part" },
                ArgvToken::Flag { flag: "--footprint", param: "footprint" },
                ArgvToken::Switch { flag: "--set-default", param: "set_default" },
                ArgvToken::Repeated { flag: "--entry", param: "entries" },
                PROPOSAL_ID_ARGV,
                RATIONALE_ARGV,
            ],
        },
        params: &[
            PATH,
            ParamSpec {
                name: "map",
                ty: ParamType::Uuid,
                required: true,
                doc: "PinPadMap UUID",
                default_json: None,
            },
            ParamSpec {
                name: "part",
                ty: ParamType::Uuid,
                required: true,
                doc: "Part UUID this PinPadMap binds",
                default_json: None,
            },
            ParamSpec {
                name: "entries",
                ty: ParamType::StrList,
                required: true,
                doc: "Mapping entry as pad_uuid:gate_uuid:pin_uuid; pin_uuid:pad_uuid is allowed only when unambiguous",
                default_json: None,
            },
            ParamSpec {
                name: "footprint",
                ty: ParamType::Uuid,
                required: false,
                doc: "Optional Footprint UUID; if omitted mappings target package pads",
                default_json: None,
            },
            ParamSpec {
                name: "set_default",
                ty: ParamType::Bool,
                required: false,
                doc: "Also set this map as the part default_pin_pad_map in the same proposal batch",
                default_json: Some("false"),
            },
            ParamSpec {
                name: "pool",
                ty: ParamType::Str,
                required: false,
                doc: "Project-local pool path",
                default_json: Some("\"pool\""),
            },
            PROPOSAL_ID,
            RATIONALE,
        ],
        schema_json_override: None,
        write_surface: Some(PROPOSAL_METADATA_WRITE),
        terminal: true,
        terminal_optional_params: &["pool", "rationale"],
        terminal_argv_override: None,
    },
    VerbSpec {
        id: "datum.proposal.defer",
        summary: "Defer one draft native-project proposal without applying it.",
        status: VerbStatus::Public,
        replacements: &[],
        retirement: None,
        dispatch: Dispatch::Cli {
            method: "defer_proposal",
            argv: &[
                ArgvToken::Lit("proposal"),
                ArgvToken::Lit("defer"),
                ArgvToken::Param("path"),
                PROPOSAL_ID_ARGV,
            ],
        },
        params: &[PATH, PROPOSAL_TARGET],
        schema_json_override: None,
        write_surface: Some(PROPOSAL_REVIEW_STATE_WRITE),
        terminal: true,
        terminal_optional_params: &[],
        terminal_argv_override: None,
    },
    VerbSpec {
        id: "datum.proposal.delete_manufacturing_plan",
        summary: "Create a draft proposal for deleting one ManufacturingPlan without mutating manufacturing plan shards.",
        status: VerbStatus::Public,
        replacements: &[],
        retirement: None,
        dispatch: Dispatch::Cli {
            method: "delete_manufacturing_plan_proposal",
            argv: &[
                ArgvToken::Lit("proposal"),
                ArgvToken::Lit("delete-manufacturing-plan"),
                ArgvToken::Param("path"),
                ArgvToken::Flag { flag: "--manufacturing-plan", param: "manufacturing_plan" },
                PROPOSAL_ID_ARGV,
                RATIONALE_ARGV,
            ],
        },
        params: &[
            PATH,
            ParamSpec {
                name: "manufacturing_plan",
                ty: ParamType::Uuid,
                required: true,
                doc: "ManufacturingPlan UUID to delete",
                default_json: None,
            },
            PROPOSAL_ID,
            RATIONALE,
        ],
        schema_json_override: None,
        write_surface: Some(PROPOSAL_METADATA_WRITE),
        terminal: true,
        terminal_optional_params: &[],
        terminal_argv_override: None,
    },
    VerbSpec {
        id: "datum.proposal.delete_output_job",
        summary: "Create a draft proposal for deleting one OutputJob without mutating the OutputJob shard.",
        status: VerbStatus::Public,
        replacements: &[],
        retirement: None,
        dispatch: Dispatch::Cli {
            method: "delete_output_job_proposal",
            argv: &[
                ArgvToken::Lit("proposal"),
                ArgvToken::Lit("delete-output-job"),
                ArgvToken::Param("path"),
                ArgvToken::Flag { flag: "--output-job", param: "output_job" },
                PROPOSAL_ID_ARGV,
                RATIONALE_ARGV,
            ],
        },
        params: &[
            PATH,
            ParamSpec {
                name: "output_job",
                ty: ParamType::Uuid,
                required: true,
                doc: "OutputJob UUID",
                default_json: None,
            },
            PROPOSAL_ID,
            RATIONALE,
        ],
        schema_json_override: None,
        write_surface: Some(PROPOSAL_METADATA_WRITE),
        terminal: true,
        terminal_optional_params: &[],
        terminal_argv_override: None,
    },
    VerbSpec {
        id: "datum.proposal.delete_panel_projection",
        summary: "Create a draft proposal for deleting one PanelProjection without mutating panel shards.",
        status: VerbStatus::Public,
        replacements: &[],
        retirement: None,
        dispatch: Dispatch::Cli {
            method: "delete_panel_projection_proposal",
            argv: &[
                ArgvToken::Lit("proposal"),
                ArgvToken::Lit("delete-panel-projection"),
                ArgvToken::Param("path"),
                ArgvToken::Flag { flag: "--panel-projection", param: "panel_projection" },
                PROPOSAL_ID_ARGV,
                RATIONALE_ARGV,
            ],
        },
        params: &[
            PATH,
            ParamSpec {
                name: "panel_projection",
                ty: ParamType::Uuid,
                required: true,
                doc: "PanelProjection UUID to delete",
                default_json: None,
            },
            PROPOSAL_ID,
            RATIONALE,
        ],
        schema_json_override: None,
        write_surface: Some(PROPOSAL_METADATA_WRITE),
        terminal: true,
        terminal_optional_params: &[],
        terminal_argv_override: None,
    },
    VerbSpec {
        id: "datum.proposal.list",
        summary: "Read resolver-discovered proposal records for a native project.",
        status: VerbStatus::Public,
        replacements: &[],
        retirement: None,
        dispatch: Dispatch::Cli {
            method: "get_proposals",
            argv: &[
                ArgvToken::Lit("proposal"),
                ArgvToken::Lit("list"),
                ArgvToken::Param("path"),
            ],
        },
        params: &[PATH],
        schema_json_override: None,
        write_surface: None,
        terminal: true,
        terminal_optional_params: &[],
        terminal_argv_override: None,
    },
    VerbSpec {
        id: "datum.proposal.preview",
        summary: "Preview one persisted native-project proposal's classified diff without writing shards.",
        status: VerbStatus::Public,
        replacements: &[],
        retirement: None,
        dispatch: Dispatch::Cli {
            method: "preview_proposal",
            argv: &[
                ArgvToken::Lit("proposal"),
                ArgvToken::Lit("preview"),
                ArgvToken::Param("path"),
                PROPOSAL_ID_ARGV,
            ],
        },
        params: &[PATH, PROPOSAL_TARGET],
        schema_json_override: None,
        write_surface: None,
        terminal: true,
        terminal_optional_params: &[],
        terminal_argv_override: None,
    },
    VerbSpec {
        id: "datum.proposal.reject",
        summary: "Reject one draft native-project proposal without applying it.",
        status: VerbStatus::Public,
        replacements: &[],
        retirement: None,
        dispatch: Dispatch::Cli {
            method: "reject_proposal",
            argv: &[
                ArgvToken::Lit("proposal"),
                ArgvToken::Lit("reject"),
                ArgvToken::Param("path"),
                PROPOSAL_ID_ARGV,
            ],
        },
        params: &[PATH, PROPOSAL_TARGET],
        schema_json_override: None,
        write_surface: Some(PROPOSAL_REVIEW_STATE_WRITE),
        terminal: true,
        terminal_optional_params: &[],
        terminal_argv_override: None,
    },
    VerbSpec {
        id: "datum.proposal.review",
        summary: "Review one persisted native-project proposal as accepted, deferred, or rejected.",
        status: VerbStatus::Public,
        replacements: &[],
        retirement: None,
        dispatch: Dispatch::Cli {
            method: "review_proposal",
            argv: &[
                ArgvToken::Lit("proposal"),
                ArgvToken::Lit("review"),
                ArgvToken::Param("path"),
                PROPOSAL_ID_ARGV,
                ArgvToken::Flag { flag: "--status", param: "status" },
            ],
        },
        params: &[
            PATH,
            PROPOSAL_TARGET,
            ParamSpec {
                name: "status",
                ty: ParamType::Str,
                required: true,
                doc: "Review status to persist: accepted, deferred, or rejected",
                default_json: None,
            },
        ],
        schema_json_override: Some(
            r#"{"type":"object","properties":{"path":{"type":"string"},"proposal":{"type":"string"},"status":{"type":"string","enum":["accepted","deferred","rejected"]}},"required":["path","proposal","status"]}"#,
        ),
        write_surface: Some(PROPOSAL_REVIEW_STATE_WRITE),
        terminal: true,
        terminal_optional_params: &[],
        terminal_argv_override: None,
    },
    VerbSpec {
        id: "datum.proposal.set_pool_pin_pad_map",
        summary: "Create a non-mutating draft proposal to update first-class native pool PinPadMap mappings.",
        status: VerbStatus::Public,
        replacements: &[],
        retirement: None,
        dispatch: Dispatch::Cli {
            method: "set_pool_pin_pad_map_proposal",
            argv: &[
                ArgvToken::Lit("proposal"),
                ArgvToken::Lit("set-pool-pin-pad-map"),
                ArgvToken::Param("path"),
                ArgvToken::Flag { flag: "--pool", param: "pool" },
                ArgvToken::Flag { flag: "--map", param: "map" },
                ArgvToken::Flag { flag: "--mode", param: "mode" },
                ArgvToken::Repeated { flag: "--entry", param: "entries" },
                PROPOSAL_ID_ARGV,
                RATIONALE_ARGV,
            ],
        },
        params: &[
            PATH,
            ParamSpec {
                name: "map",
                ty: ParamType::Uuid,
                required: true,
                doc: "PinPadMap UUID",
                default_json: None,
            },
            ParamSpec {
                name: "mode",
                ty: ParamType::Str,
                required: false,
                doc: "Merge listed mappings or replace the full mapping table",
                default_json: Some("\"merge\""),
            },
            ParamSpec {
                name: "entries",
                ty: ParamType::StrList,
                required: true,
                doc: "Mapping entry as pad_uuid:gate_uuid:pin_uuid; pin_uuid:pad_uuid is allowed only when unambiguous",
                default_json: None,
            },
            ParamSpec {
                name: "pool",
                ty: ParamType::Str,
                required: false,
                doc: "Project-local pool path",
                default_json: Some("\"pool\""),
            },
            PROPOSAL_ID,
            RATIONALE,
        ],
        schema_json_override: None,
        write_surface: Some(PROPOSAL_METADATA_WRITE),
        terminal: true,
        terminal_optional_params: &["pool", "mode", "rationale"],
        terminal_argv_override: None,
    },
    VerbSpec {
        id: "datum.proposal.show",
        summary: "Show one persisted native-project proposal plus validation state.",
        status: VerbStatus::Public,
        replacements: &[],
        retirement: None,
        dispatch: Dispatch::Cli {
            method: "show_proposal",
            argv: &[
                ArgvToken::Lit("proposal"),
                ArgvToken::Lit("show"),
                ArgvToken::Param("path"),
                PROPOSAL_ID_ARGV,
            ],
        },
        params: &[PATH, PROPOSAL_TARGET],
        schema_json_override: None,
        write_surface: None,
        terminal: true,
        terminal_optional_params: &[],
        terminal_argv_override: None,
    },
    VerbSpec {
        id: "datum.proposal.update_manufacturing_plan",
        summary: "Create a draft proposal for a ManufacturingPlan update without mutating manufacturing plan shards.",
        status: VerbStatus::Public,
        replacements: &[],
        retirement: None,
        dispatch: Dispatch::Cli {
            method: "update_manufacturing_plan_proposal",
            argv: &[
                ArgvToken::Lit("proposal"),
                ArgvToken::Lit("update-manufacturing-plan"),
                ArgvToken::Param("path"),
                ArgvToken::Flag { flag: "--manufacturing-plan", param: "manufacturing_plan" },
                ArgvToken::Flag { flag: "--name", param: "name" },
                ArgvToken::Flag { flag: "--prefix", param: "prefix" },
                ArgvToken::Flag { flag: "--variant", param: "variant" },
                ArgvToken::Switch { flag: "--clear-variant", param: "clear_variant" },
                ArgvToken::Flag { flag: "--panel-projection", param: "panel_projection" },
                ArgvToken::Switch { flag: "--clear-panel-projection", param: "clear_panel_projection" },
                PROPOSAL_ID_ARGV,
                RATIONALE_ARGV,
            ],
        },
        params: &[
            PATH,
            ParamSpec {
                name: "manufacturing_plan",
                ty: ParamType::Uuid,
                required: true,
                doc: "ManufacturingPlan UUID to update",
                default_json: None,
            },
            ParamSpec {
                name: "name",
                ty: ParamType::Str,
                required: false,
                doc: "Replacement human-readable manufacturing plan name",
                default_json: None,
            },
            ParamSpec {
                name: "prefix",
                ty: ParamType::Str,
                required: false,
                doc: "Replacement deterministic manufacturing artifact filename prefix",
                default_json: None,
            },
            ParamSpec {
                name: "variant",
                ty: ParamType::Uuid,
                required: false,
                doc: "Replacement variant UUID this plan targets",
                default_json: None,
            },
            ParamSpec {
                name: "clear_variant",
                ty: ParamType::Bool,
                required: false,
                doc: "Clear the variant target",
                default_json: None,
            },
            ParamSpec {
                name: "panel_projection",
                ty: ParamType::Uuid,
                required: false,
                doc: "Replacement panel projection UUID this plan targets",
                default_json: None,
            },
            ParamSpec {
                name: "clear_panel_projection",
                ty: ParamType::Bool,
                required: false,
                doc: "Clear the panel target and retarget the current board",
                default_json: None,
            },
            PROPOSAL_ID,
            RATIONALE,
        ],
        schema_json_override: None,
        write_surface: Some(PROPOSAL_METADATA_WRITE),
        terminal: true,
        terminal_optional_params: &["name"],
        terminal_argv_override: None,
    },
    VerbSpec {
        id: "datum.proposal.update_output_job",
        summary: "Create a draft proposal for an OutputJob settings update without mutating the OutputJob shard.",
        status: VerbStatus::Public,
        replacements: &[],
        retirement: None,
        dispatch: Dispatch::Cli {
            method: "update_output_job_proposal",
            argv: &[
                ArgvToken::Lit("proposal"),
                ArgvToken::Lit("update-output-job"),
                ArgvToken::Param("path"),
                ArgvToken::Flag { flag: "--output-job", param: "output_job" },
                ArgvToken::Flag { flag: "--name", param: "name" },
                ArgvToken::Flag { flag: "--output-dir", param: "output_dir" },
                ArgvToken::Flag { flag: "--manufacturing-plan", param: "manufacturing_plan" },
                ArgvToken::Flag { flag: "--variant", param: "variant" },
                ArgvToken::Switch { flag: "--clear-manufacturing-plan", param: "clear_manufacturing_plan" },
                ArgvToken::Switch { flag: "--clear-variant", param: "clear_variant" },
                ArgvToken::Switch { flag: "--clear-output-dir", param: "clear_output_dir" },
                PROPOSAL_ID_ARGV,
                RATIONALE_ARGV,
            ],
        },
        params: &[
            PATH,
            ParamSpec {
                name: "output_job",
                ty: ParamType::Uuid,
                required: true,
                doc: "OutputJob UUID",
                default_json: None,
            },
            ParamSpec {
                name: "name",
                ty: ParamType::Str,
                required: false,
                doc: "Replacement human-readable output job name",
                default_json: None,
            },
            ParamSpec {
                name: "output_dir",
                ty: ParamType::Str,
                required: false,
                doc: "Replacement preferred output directory for generated artifacts",
                default_json: None,
            },
            ParamSpec {
                name: "manufacturing_plan",
                ty: ParamType::Uuid,
                required: false,
                doc: "Replacement manufacturing plan UUID this output job executes",
                default_json: None,
            },
            ParamSpec {
                name: "clear_manufacturing_plan",
                ty: ParamType::Bool,
                required: false,
                doc: "Clear any linked manufacturing plan",
                default_json: None,
            },
            ParamSpec {
                name: "clear_output_dir",
                ty: ParamType::Bool,
                required: false,
                doc: "Clear any stored output directory so launchers use their default",
                default_json: None,
            },
            PROPOSAL_ID,
            RATIONALE,
            ParamSpec {
                name: "variant",
                ty: ParamType::Uuid,
                required: false,
                doc: "Replacement variant overlay UUID this output job targets",
                default_json: None,
            },
            ParamSpec {
                name: "clear_variant",
                ty: ParamType::Bool,
                required: false,
                doc: "Clear any linked variant",
                default_json: None,
            },
        ],
        schema_json_override: None,
        write_surface: Some(PROPOSAL_METADATA_WRITE),
        terminal: true,
        terminal_optional_params: &["name"],
        terminal_argv_override: None,
    },
    VerbSpec {
        id: "datum.proposal.update_panel_projection",
        summary: "Create a draft proposal for a PanelProjection update without mutating panel shards.",
        status: VerbStatus::Public,
        replacements: &[],
        retirement: None,
        dispatch: Dispatch::Cli {
            method: "update_panel_projection_proposal",
            argv: &[
                ArgvToken::Lit("proposal"),
                ArgvToken::Lit("update-panel-projection"),
                ArgvToken::Param("path"),
                ArgvToken::Flag { flag: "--panel-projection", param: "panel_projection" },
                ArgvToken::Flag { flag: "--name", param: "name" },
                ArgvToken::Flag { flag: "--board", param: "board" },
                ArgvToken::Flag { flag: "--x-nm", param: "x_nm" },
                ArgvToken::Flag { flag: "--y-nm", param: "y_nm" },
                ArgvToken::Flag { flag: "--rotation-deg", param: "rotation_deg" },
                PROPOSAL_ID_ARGV,
                RATIONALE_ARGV,
            ],
        },
        params: &[
            PATH,
            ParamSpec {
                name: "panel_projection",
                ty: ParamType::Uuid,
                required: true,
                doc: "PanelProjection UUID to update",
                default_json: None,
            },
            ParamSpec {
                name: "name",
                ty: ParamType::Str,
                required: false,
                doc: "Replacement human-readable panel projection name",
                default_json: None,
            },
            ParamSpec {
                name: "board",
                ty: ParamType::Uuid,
                required: false,
                doc: "Replacement board UUID for the first panel instance",
                default_json: None,
            },
            ParamSpec {
                name: "x_nm",
                ty: ParamType::Int,
                required: false,
                doc: "Replacement first board instance X offset in nanometers",
                default_json: None,
            },
            ParamSpec {
                name: "y_nm",
                ty: ParamType::Int,
                required: false,
                doc: "Replacement first board instance Y offset in nanometers",
                default_json: None,
            },
            ParamSpec {
                name: "rotation_deg",
                ty: ParamType::Int,
                required: false,
                doc: "Replacement first board instance rotation in degrees",
                default_json: None,
            },
            PROPOSAL_ID,
            RATIONALE,
        ],
        schema_json_override: None,
        write_surface: Some(PROPOSAL_METADATA_WRITE),
        terminal: true,
        terminal_optional_params: &["name"],
        terminal_argv_override: None,
    },
    VerbSpec {
        id: "datum.proposal.validate",
        summary: "Validate one persisted native-project proposal against the current model revision.",
        status: VerbStatus::Public,
        replacements: &[],
        retirement: None,
        dispatch: Dispatch::Cli {
            method: "validate_proposal",
            argv: &[
                ArgvToken::Lit("proposal"),
                ArgvToken::Lit("validate"),
                ArgvToken::Param("path"),
                PROPOSAL_ID_ARGV,
            ],
        },
        params: &[PATH, PROPOSAL_TARGET],
        schema_json_override: None,
        write_surface: None,
        terminal: true,
        terminal_optional_params: &[],
        terminal_argv_override: None,
    },
];
