from __future__ import annotations
import unittest
from tool_dispatch import registered_tool_names


class TestDispatchDatumTaxonomyCatalog(unittest.TestCase):
    def test_catalog_lists_canonical_datum_tools_first(self) -> None:
        tool_names = registered_tool_names()
        # The registry-generated verb families (artifact/check/context/journal/
        # manufacturing/output_job/session) are appended as one sorted block at
        # the end of the canonical datum.* specs; hand-written canonical specs
        # still lead the catalog and every datum.* tool precedes every
        # compatibility tool.
        self.assertEqual(tool_names[:4], ["datum.query.board_summary", "datum.query.components", "datum.query.netlist", "datum.query.schematic_summary"])
        generated_context = ["datum.context.get", "datum.context.refresh", "datum.context.session_activity", "datum.context.session_events"]
        self.assertEqual(tool_names[277:281], generated_context)
        first_compatibility = next(index for index, name in enumerate(tool_names) if not name.startswith("datum."))
        self.assertEqual(first_compatibility, 332)
        self.assertEqual(tool_names[45:90], "datum.pcb.place_component datum.pcb.generate_board_components datum.pcb.move_component datum.pcb.rotate_component datum.pcb.flip_component datum.pcb.delete_component datum.pcb.set_component_reference datum.pcb.set_component_value datum.pcb.set_component_part datum.pcb.set_component_package datum.pcb.lock_component datum.pcb.unlock_component datum.pcb.draw_track datum.pcb.edit_track datum.pcb.delete_track datum.pcb.place_via datum.pcb.edit_via datum.pcb.delete_via datum.pcb.place_zone datum.pcb.edit_zone datum.pcb.delete_zone datum.pcb.place_pad datum.pcb.edit_pad datum.pcb.delete_pad datum.pcb.set_pad_net datum.pcb.clear_pad_net datum.pcb.place_net datum.pcb.edit_net datum.pcb.delete_net datum.pcb.set_board_name datum.pcb.set_outline datum.pcb.set_stackup datum.pcb.add_default_top_stackup datum.pcb.place_keepout datum.pcb.edit_keepout datum.pcb.delete_keepout datum.pcb.place_dimension datum.pcb.edit_dimension datum.pcb.delete_dimension datum.pcb.place_text datum.pcb.edit_text datum.pcb.delete_text datum.pcb.place_net_class datum.pcb.edit_net_class datum.pcb.delete_net_class".split())
        self.assertEqual(tool_names[90:150], "datum.component_instance.bind datum.component_instance.set datum.component_instance.delete datum.library.list_objects datum.library.show_object datum.library.pool_models datum.library.gc_pool_models datum.library.create_object datum.library.create_unit datum.library.set_unit_pin datum.library.create_symbol datum.library.add_symbol_line datum.library.add_symbol_rect datum.library.add_symbol_circle datum.library.add_symbol_arc datum.library.add_symbol_polygon datum.library.add_symbol_text datum.library.set_symbol_pin_anchor datum.library.create_entity datum.library.create_padstack datum.library.create_package datum.library.create_footprint datum.library.set_footprint_pad datum.library.set_footprint_courtyard_rect datum.library.set_footprint_courtyard_polygon datum.library.add_footprint_silkscreen_line datum.library.add_footprint_silkscreen_rect datum.library.add_footprint_silkscreen_circle datum.library.add_footprint_silkscreen_polygon datum.library.set_package_pad datum.library.set_package_courtyard_rect datum.library.set_package_courtyard_polygon datum.library.add_package_silkscreen_line datum.library.add_package_silkscreen_rect datum.library.add_package_silkscreen_polygon datum.library.add_package_silkscreen_circle datum.library.add_package_silkscreen_arc datum.library.add_package_silkscreen_text datum.library.add_package_model_3d datum.library.set_package_body_heights datum.library.create_part datum.library.set_part_metadata datum.library.set_part_parametric datum.library.set_part_orderable_mpns datum.library.set_part_tags datum.library.set_part_packaging_options datum.library.set_part_supply_chain datum.library.set_part_behavioural_models datum.library.attach_part_model datum.library.detach_part_model datum.library.set_part_thermal datum.library.set_part_pad_map_entry datum.library.set_part_pad_map datum.library.create_pin_pad_map datum.library.set_pin_pad_map datum.project.validate datum.project.create_pool_pin_pad_map datum.project.set_pool_pin_pad_map datum.library.set_object datum.library.delete_object".split())
        self.assertEqual(tool_names[150:212], "datum.schematic.create_sheet datum.schematic.delete_sheet datum.schematic.rename_sheet datum.schematic.create_sheet_definition datum.schematic.create_sheet_instance datum.schematic.delete_sheet_instance datum.schematic.move_sheet_instance datum.schematic.bind_sheet_instance_port datum.schematic.unbind_sheet_instance_port datum.schematic.draw_wire datum.schematic.delete_wire datum.schematic.place_junction datum.schematic.delete_junction datum.schematic.place_noconnect datum.schematic.delete_noconnect datum.schematic.place_label datum.schematic.rename_label datum.schematic.delete_label datum.schematic.place_port datum.schematic.edit_port datum.schematic.delete_port datum.schematic.create_bus datum.schematic.edit_bus_members datum.schematic.delete_bus datum.schematic.place_bus_entry datum.schematic.delete_bus_entry datum.schematic.place_text datum.schematic.edit_text datum.schematic.delete_text datum.schematic.place_drawing_line datum.schematic.place_drawing_rect datum.schematic.place_drawing_circle datum.schematic.place_drawing_arc datum.schematic.edit_drawing_line datum.schematic.edit_drawing_rect datum.schematic.edit_drawing_circle datum.schematic.edit_drawing_arc datum.schematic.delete_drawing datum.schematic.place_symbol datum.schematic.move_symbol datum.schematic.rotate_symbol datum.schematic.mirror_symbol datum.schematic.delete_symbol datum.schematic.set_symbol_reference datum.schematic.set_symbol_value datum.schematic.set_symbol_display_mode datum.schematic.set_symbol_hidden_power_behavior datum.schematic.set_symbol_unit datum.schematic.clear_symbol_unit datum.schematic.set_symbol_gate datum.schematic.clear_symbol_gate datum.schematic.set_symbol_entity datum.schematic.clear_symbol_entity datum.schematic.set_symbol_part datum.schematic.clear_symbol_part datum.schematic.set_symbol_lib_id datum.schematic.clear_symbol_lib_id datum.schematic.set_pin_override datum.schematic.clear_pin_override datum.schematic.add_symbol_field datum.schematic.edit_symbol_field datum.schematic.delete_symbol_field".split())
