"""Proposal MCP tool schemas."""

PROPOSAL_TOOL_SCHEMAS = {
    "create_proposal": {
        "description": "Create a non-mutating draft proposal from an OperationBatch JSON file.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "path": {"type": "string"},
                "batch": {"type": "string"},
                "rationale": {"type": "string"},
                "proposal": {"type": "string"},
                "source": {"type": "string", "enum": ["manual", "cli", "tool", "assistant", "check", "import"]},
                "checks_run": {"type": "array", "items": {"type": "string"}},
                "finding_fingerprints": {"type": "array", "items": {"type": "string"}},
            },
            "required": ["path", "batch", "rationale"],
        },
        "x_dispatch_args": ["path", "batch", "rationale", "proposal", "source", "checks_run", "finding_fingerprints"],
        "x_dispatch_defaults": {"source": "tool", "checks_run": [], "finding_fingerprints": []},
    },
    "create_draw_wire_proposal": {
        "description": "Create a non-mutating draft proposal to draw one native-project schematic wire.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "path": {"type": "string"},
                "sheet": {"type": "string"},
                "from_x_nm": {"type": "integer"},
                "from_y_nm": {"type": "integer"},
                "to_x_nm": {"type": "integer"},
                "to_y_nm": {"type": "integer"},
                "proposal": {"type": ["string", "null"]},
                "rationale": {"type": ["string", "null"]},
            },
            "required": ["path", "sheet", "from_x_nm", "from_y_nm", "to_x_nm", "to_y_nm"],
        },
        "x_dispatch_args": ["path", "sheet", "from_x_nm", "from_y_nm", "to_x_nm", "to_y_nm", "proposal", "rationale"],
    },
    "create_place_label_proposal": {
        "description": "Create a non-mutating draft proposal to place one native-project schematic label.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "path": {"type": "string"},
                "sheet": {"type": "string"},
                "name": {"type": "string"},
                "x_nm": {"type": "integer"},
                "y_nm": {"type": "integer"},
                "kind": {"type": ["string", "null"]},
                "proposal": {"type": ["string", "null"]},
                "rationale": {"type": ["string", "null"]},
            },
            "required": ["path", "sheet", "name", "x_nm", "y_nm"],
        },
        "x_dispatch_args": ["path", "sheet", "name", "x_nm", "y_nm", "kind", "proposal", "rationale"],
    },
    "create_place_symbol_proposal": {
        "description": "Create a non-mutating draft proposal to place one native-project schematic symbol.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "path": {"type": "string"},
                "sheet": {"type": "string"},
                "reference": {"type": "string"},
                "value": {"type": "string"},
                "x_nm": {"type": "integer"},
                "y_nm": {"type": "integer"},
                "lib_id": {"type": ["string", "null"]},
                "rotation_deg": {"type": ["integer", "null"]},
                "mirrored": {"type": ["boolean", "null"]},
                "proposal": {"type": ["string", "null"]},
                "rationale": {"type": ["string", "null"]},
            },
            "required": ["path", "sheet", "reference", "value", "x_nm", "y_nm"],
        },
        "x_dispatch_args": ["path", "sheet", "reference", "value", "x_nm", "y_nm", "lib_id", "rotation_deg", "mirrored", "proposal", "rationale"],
    },
    "create_board_component_replacement_proposal": {
        "description": "Create a non-mutating draft proposal to replace one native-project board component package, part, and/or value.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "path": {"type": "string"},
                "component": {"type": "string"},
                "package": {"type": ["string", "null"]},
                "part": {"type": ["string", "null"]},
                "value": {"type": ["string", "null"]},
                "proposal": {"type": ["string", "null"]},
                "rationale": {"type": ["string", "null"]},
            },
            "required": ["path", "component"],
        },
        "x_dispatch_args": ["path", "component", "package", "part", "value", "proposal", "rationale"],
    },
    "create_board_component_replacements_proposal": {
        "description": "Create one non-mutating draft proposal to replace multiple native-project board component package, part, and/or value sets.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "path": {"type": "string"},
                "replacements": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "component": {"type": "string"},
                            "package": {"type": ["string", "null"]},
                            "part": {"type": ["string", "null"]},
                            "value": {"type": ["string", "null"]},
                        },
                        "required": ["component"],
                    },
                },
                "proposal": {"type": ["string", "null"]},
                "rationale": {"type": ["string", "null"]},
            },
            "required": ["path", "replacements"],
        },
        "x_dispatch_args": ["path", "replacements", "proposal", "rationale"],
    },
    "create_board_component_replacement_plan_proposal": {
        "description": "Create one non-mutating draft proposal from replacement-plan shaped component selections.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "path": {"type": "string"},
                "selections": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "uuid": {"type": "string"},
                            "package_uuid": {"type": ["string", "null"]},
                            "part_uuid": {"type": ["string", "null"]},
                            "value": {"type": ["string", "null"]},
                        },
                        "required": ["uuid"],
                    },
                },
                "proposal": {"type": ["string", "null"]},
                "rationale": {"type": ["string", "null"]},
            },
            "required": ["path", "selections"],
        },
        "x_dispatch_args": ["path", "selections", "proposal", "rationale"],
    },
    "create_pool_library_object_proposal": {
        "description": "Create a non-mutating draft proposal to author one raw native pool-library object.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "path": {"type": "string"},
                "pool": {"type": ["string", "null"]},
                "kind": {"type": "string"},
                "object": {"type": "string"},
                "from_json": {"type": "string"},
                "proposal": {"type": ["string", "null"]},
                "rationale": {"type": ["string", "null"]},
            },
            "required": ["path", "kind", "object", "from_json"],
        },
        "x_dispatch_args": [
            "path",
            "kind",
            "object",
            "from_json",
            "pool",
            "proposal",
            "rationale",
        ],
        "x_dispatch_defaults": {"pool": "pool"},
    },
    "create_pool_unit_proposal": {
        "description": "Create a non-mutating draft proposal to author one native pool unit.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "path": {"type": "string"},
                "pool": {"type": ["string", "null"]},
                "unit": {"type": "string"},
                "name": {"type": "string"},
                "manufacturer": {"type": ["string", "null"]},
                "proposal": {"type": ["string", "null"]},
                "rationale": {"type": ["string", "null"]},
            },
            "required": ["path", "unit", "name"],
        },
        "x_dispatch_args": [
            "path",
            "unit",
            "name",
            "manufacturer",
            "pool",
            "proposal",
            "rationale",
        ],
        "x_dispatch_defaults": {"pool": "pool", "manufacturer": ""},
    },
    "create_pool_symbol_proposal": {
        "description": "Create a non-mutating draft proposal to author one native pool symbol for an existing pool unit.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "path": {"type": "string"},
                "pool": {"type": ["string", "null"]},
                "symbol": {"type": "string"},
                "unit": {"type": "string"},
                "name": {"type": "string"},
                "proposal": {"type": ["string", "null"]},
                "rationale": {"type": ["string", "null"]},
            },
            "required": ["path", "symbol", "unit", "name"],
        },
        "x_dispatch_args": [
            "path",
            "symbol",
            "unit",
            "name",
            "pool",
            "proposal",
            "rationale",
        ],
        "x_dispatch_defaults": {"pool": "pool"},
    },
    "create_pool_entity_proposal": {
        "description": "Create a non-mutating draft proposal to author one native pool entity for an existing unit/symbol pair.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "path": {"type": "string"},
                "pool": {"type": ["string", "null"]},
                "entity": {"type": "string"},
                "gate": {"type": "string"},
                "unit": {"type": "string"},
                "symbol": {"type": "string"},
                "name": {"type": "string"},
                "prefix": {"type": "string"},
                "manufacturer": {"type": ["string", "null"]},
                "gate_name": {"type": ["string", "null"]},
                "proposal": {"type": ["string", "null"]},
                "rationale": {"type": ["string", "null"]},
            },
            "required": ["path", "entity", "gate", "unit", "symbol", "name", "prefix"],
        },
        "x_dispatch_args": [
            "path",
            "entity",
            "gate",
            "unit",
            "symbol",
            "name",
            "prefix",
            "manufacturer",
            "gate_name",
            "pool",
            "proposal",
            "rationale",
        ],
        "x_dispatch_defaults": {"pool": "pool", "manufacturer": "", "gate_name": "A"},
    },
    "create_pool_padstack_proposal": {
        "description": "Create a non-mutating draft proposal to author one native pool padstack.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "path": {"type": "string"},
                "pool": {"type": ["string", "null"]},
                "padstack": {"type": "string"},
                "name": {"type": "string"},
                "aperture": {"type": ["string", "null"]},
                "diameter_nm": {"type": ["integer", "null"]},
                "width_nm": {"type": ["integer", "null"]},
                "height_nm": {"type": ["integer", "null"]},
                "drill_nm": {"type": ["integer", "null"]},
                "proposal": {"type": ["string", "null"]},
                "rationale": {"type": ["string", "null"]},
            },
            "required": ["path", "padstack", "name"],
        },
        "x_dispatch_args": [
            "path",
            "padstack",
            "name",
            "aperture",
            "diameter_nm",
            "width_nm",
            "height_nm",
            "drill_nm",
            "pool",
            "proposal",
            "rationale",
        ],
        "x_dispatch_defaults": {"pool": "pool"},
    },
    "create_pool_package_proposal": {
        "description": "Create a non-mutating draft proposal to author one native pool package body record; optional pad/padstack fields are legacy land-pattern compatibility input.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "path": {"type": "string"},
                "pool": {"type": ["string", "null"]},
                "package": {"type": "string"},
                "name": {"type": "string"},
                "pad": {"type": ["string", "null"]},
                "padstack": {"type": ["string", "null"]},
                "pad_name": {"type": ["string", "null"]},
                "x_nm": {"type": ["integer", "null"]},
                "y_nm": {"type": ["integer", "null"]},
                "layer": {"type": ["integer", "null"]},
                "proposal": {"type": ["string", "null"]},
                "rationale": {"type": ["string", "null"]},
            },
            "required": ["path", "package", "name"],
        },
        "x_dispatch_args": [
            "path",
            "package",
            "name",
            "pad",
            "padstack",
            "pad_name",
            "x_nm",
            "y_nm",
            "layer",
            "pool",
            "proposal",
            "rationale",
        ],
        "x_dispatch_defaults": {"pool": "pool", "pad_name": "1", "x_nm": 0, "y_nm": 0, "layer": 1},
    },
    "create_pool_footprint_proposal": {
        "description": "Create a non-mutating draft proposal to author one native pool footprint.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "path": {"type": "string"},
                "pool": {"type": ["string", "null"]},
                "footprint": {"type": "string"},
                "package": {"type": "string"},
                "name": {"type": "string"},
                "proposal": {"type": ["string", "null"]},
                "rationale": {"type": ["string", "null"]},
            },
            "required": ["path", "footprint", "package", "name"],
        },
        "x_dispatch_args": [
            "path",
            "footprint",
            "package",
            "name",
            "pool",
            "proposal",
            "rationale",
        ],
        "x_dispatch_defaults": {"pool": "pool"},
    },
    "set_pool_footprint_pad_proposal": {
        "description": "Create a non-mutating draft proposal to set one native pool footprint pad entry.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "path": {"type": "string"},
                "pool": {"type": ["string", "null"]},
                "footprint": {"type": "string"},
                "pad": {"type": "string"},
                "padstack": {"type": "string"},
                "pad_name": {"type": ["string", "null"]},
                "x_nm": {"type": ["integer", "null"]},
                "y_nm": {"type": ["integer", "null"]},
                "layer": {"type": ["integer", "null"]},
                "proposal": {"type": ["string", "null"]},
                "rationale": {"type": ["string", "null"]},
            },
            "required": ["path", "footprint", "pad", "padstack"],
        },
        "x_dispatch_args": [
            "path",
            "footprint",
            "pad",
            "padstack",
            "pad_name",
            "x_nm",
            "y_nm",
            "layer",
            "pool",
            "proposal",
            "rationale",
        ],
        "x_dispatch_defaults": {"pool": "pool", "pad_name": "1", "x_nm": 0, "y_nm": 0, "layer": 1},
    },
    "set_pool_footprint_courtyard_rect_proposal": {
        "description": "Create a non-mutating draft proposal to set rectangular native pool footprint courtyard geometry.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "path": {"type": "string"},
                "pool": {"type": ["string", "null"]},
                "footprint": {"type": "string"},
                "min_x_nm": {"type": "integer"},
                "min_y_nm": {"type": "integer"},
                "max_x_nm": {"type": "integer"},
                "max_y_nm": {"type": "integer"},
                "proposal": {"type": ["string", "null"]},
                "rationale": {"type": ["string", "null"]},
            },
            "required": ["path", "footprint", "min_x_nm", "min_y_nm", "max_x_nm", "max_y_nm"],
        },
        "x_dispatch_args": [
            "path",
            "footprint",
            "min_x_nm",
            "min_y_nm",
            "max_x_nm",
            "max_y_nm",
            "pool",
            "proposal",
            "rationale",
        ],
        "x_dispatch_defaults": {"pool": "pool"},
    },
    "set_pool_footprint_courtyard_polygon_proposal": {
        "description": "Create a non-mutating draft proposal to set polygon native pool footprint courtyard geometry.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "path": {"type": "string"},
                "pool": {"type": ["string", "null"]},
                "footprint": {"type": "string"},
                "vertices": {"type": "string"},
                "proposal": {"type": ["string", "null"]},
                "rationale": {"type": ["string", "null"]},
            },
            "required": ["path", "footprint", "vertices"],
        },
        "x_dispatch_args": [
            "path",
            "footprint",
            "vertices",
            "pool",
            "proposal",
            "rationale",
        ],
        "x_dispatch_defaults": {"pool": "pool"},
    },
    "add_pool_footprint_silkscreen_line_proposal": {
        "description": "Create a non-mutating draft proposal to append one native pool footprint silkscreen line primitive.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "path": {"type": "string"},
                "pool": {"type": ["string", "null"]},
                "footprint": {"type": "string"},
                "from_x_nm": {"type": "integer"},
                "from_y_nm": {"type": "integer"},
                "to_x_nm": {"type": "integer"},
                "to_y_nm": {"type": "integer"},
                "width_nm": {"type": "integer"},
                "proposal": {"type": ["string", "null"]},
                "rationale": {"type": ["string", "null"]},
            },
            "required": ["path", "footprint", "from_x_nm", "from_y_nm", "to_x_nm", "to_y_nm", "width_nm"],
        },
        "x_dispatch_args": [
            "path",
            "footprint",
            "from_x_nm",
            "from_y_nm",
            "to_x_nm",
            "to_y_nm",
            "width_nm",
            "pool",
            "proposal",
            "rationale",
        ],
        "x_dispatch_defaults": {"pool": "pool"},
    },
    "add_pool_footprint_silkscreen_rect_proposal": {
        "description": "Create a non-mutating draft proposal to append one native pool footprint silkscreen rectangle primitive.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "path": {"type": "string"}, "pool": {"type": ["string", "null"]}, "footprint": {"type": "string"},
                "min_x_nm": {"type": "integer"}, "min_y_nm": {"type": "integer"},
                "max_x_nm": {"type": "integer"}, "max_y_nm": {"type": "integer"},
                "width_nm": {"type": "integer"},
                "proposal": {"type": ["string", "null"]}, "rationale": {"type": ["string", "null"]},
            },
            "required": ["path", "footprint", "min_x_nm", "min_y_nm", "max_x_nm", "max_y_nm", "width_nm"],
        },
        "x_dispatch_args": ["path", "footprint", "min_x_nm", "min_y_nm", "max_x_nm", "max_y_nm", "width_nm", "pool", "proposal", "rationale"],
        "x_dispatch_defaults": {"pool": "pool"},
    },
    "add_pool_footprint_silkscreen_circle_proposal": {
        "description": "Create a non-mutating draft proposal to append one native pool footprint silkscreen circle primitive.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "path": {"type": "string"}, "pool": {"type": ["string", "null"]}, "footprint": {"type": "string"},
                "center_x_nm": {"type": "integer"}, "center_y_nm": {"type": "integer"},
                "radius_nm": {"type": "integer"}, "width_nm": {"type": "integer"},
                "proposal": {"type": ["string", "null"]}, "rationale": {"type": ["string", "null"]},
            },
            "required": ["path", "footprint", "center_x_nm", "center_y_nm", "radius_nm", "width_nm"],
        },
        "x_dispatch_args": ["path", "footprint", "center_x_nm", "center_y_nm", "radius_nm", "width_nm", "pool", "proposal", "rationale"],
        "x_dispatch_defaults": {"pool": "pool"},
    },
    "add_pool_footprint_silkscreen_polygon_proposal": {
        "description": "Create a non-mutating draft proposal to append one native pool footprint silkscreen polygon or polyline primitive.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "path": {"type": "string"}, "pool": {"type": ["string", "null"]}, "footprint": {"type": "string"},
                "vertices": {"type": "string"}, "closed": {"type": "boolean"}, "width_nm": {"type": "integer"},
                "proposal": {"type": ["string", "null"]}, "rationale": {"type": ["string", "null"]},
            },
            "required": ["path", "footprint", "vertices", "closed", "width_nm"],
        },
        "x_dispatch_args": ["path", "footprint", "vertices", "closed", "width_nm", "pool", "proposal", "rationale"],
        "x_dispatch_defaults": {"pool": "pool"},
    },
    "set_pool_package_pad_proposal": {
        "description": "Create a non-mutating draft proposal to add one native pool package pad entry.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "path": {"type": "string"},
                "pool": {"type": ["string", "null"]},
                "package": {"type": "string"},
                "pad": {"type": "string"},
                "padstack": {"type": "string"},
                "pad_name": {"type": ["string", "null"]},
                "x_nm": {"type": ["integer", "null"]},
                "y_nm": {"type": ["integer", "null"]},
                "layer": {"type": ["integer", "null"]},
                "proposal": {"type": ["string", "null"]},
                "rationale": {"type": ["string", "null"]},
            },
            "required": ["path", "package", "pad", "padstack"],
        },
        "x_dispatch_args": [
            "path",
            "package",
            "pad",
            "padstack",
            "pad_name",
            "x_nm",
            "y_nm",
            "layer",
            "pool",
            "proposal",
            "rationale",
        ],
        "x_dispatch_defaults": {"pool": "pool", "pad_name": "1", "x_nm": 0, "y_nm": 0, "layer": 1},
    },
    "set_pool_package_courtyard_rect_proposal": {
        "description": "Create a non-mutating draft proposal to set rectangular native pool package courtyard geometry.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "path": {"type": "string"},
                "pool": {"type": ["string", "null"]},
                "package": {"type": "string"},
                "min_x_nm": {"type": "integer"},
                "min_y_nm": {"type": "integer"},
                "max_x_nm": {"type": "integer"},
                "max_y_nm": {"type": "integer"},
                "proposal": {"type": ["string", "null"]},
                "rationale": {"type": ["string", "null"]},
            },
            "required": ["path", "package", "min_x_nm", "min_y_nm", "max_x_nm", "max_y_nm"],
        },
        "x_dispatch_args": [
            "path",
            "package",
            "min_x_nm",
            "min_y_nm",
            "max_x_nm",
            "max_y_nm",
            "pool",
            "proposal",
            "rationale",
        ],
        "x_dispatch_defaults": {"pool": "pool"},
    },
    "set_pool_package_courtyard_polygon_proposal": {
        "description": "Create a non-mutating draft proposal to set polygon native pool package courtyard geometry.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "path": {"type": "string"},
                "pool": {"type": ["string", "null"]},
                "package": {"type": "string"},
                "vertices": {"type": "string"},
                "proposal": {"type": ["string", "null"]},
                "rationale": {"type": ["string", "null"]},
            },
            "required": ["path", "package", "vertices"],
        },
        "x_dispatch_args": [
            "path",
            "package",
            "vertices",
            "pool",
            "proposal",
            "rationale",
        ],
        "x_dispatch_defaults": {"pool": "pool"},
    },
    "get_proposals": {
        "description": "Read resolver-discovered proposal records for a native project.",
        "inputSchema": {
            "type": "object",
            "properties": {"path": {"type": "string"}},
            "required": ["path"],
        },
    },
    "show_proposal": {
        "description": "Show one persisted native-project proposal plus validation state.",
        "inputSchema": {
            "type": "object",
            "properties": {"path": {"type": "string"}, "proposal": {"type": "string"}},
            "required": ["path", "proposal"],
        },
    },
    "preview_proposal": {
        "description": "Preview one persisted native-project proposal's classified diff without writing shards.",
        "inputSchema": {
            "type": "object",
            "properties": {"path": {"type": "string"}, "proposal": {"type": "string"}},
            "required": ["path", "proposal"],
        },
    },
    "validate_proposal": {
        "description": "Validate one persisted native-project proposal against the current model revision.",
        "inputSchema": {
            "type": "object",
            "properties": {"path": {"type": "string"}, "proposal": {"type": "string"}},
            "required": ["path", "proposal"],
        },
    },
    "defer_proposal": {
        "description": "Defer one draft native-project proposal without applying it.",
        "inputSchema": {
            "type": "object",
            "properties": {"path": {"type": "string"}, "proposal": {"type": "string"}},
            "required": ["path", "proposal"],
        },
    },
    "reject_proposal": {
        "description": "Reject one draft native-project proposal without applying it.",
        "inputSchema": {
            "type": "object",
            "properties": {"path": {"type": "string"}, "proposal": {"type": "string"}},
            "required": ["path", "proposal"],
        },
    },
    "review_proposal": {
        "description": "Review one persisted native-project proposal as accepted, deferred, or rejected.",
        "inputSchema": {
            "type": "object",
            "properties": {"path": {"type": "string"}, "proposal": {"type": "string"}, "status": {"type": "string", "enum": ["accepted", "deferred", "rejected"]}},
            "required": ["path", "proposal", "status"],
        },
    },
    "apply_proposal": {
        "description": "Apply one accepted persisted native-project proposal through the generic proposal gateway.",
        "inputSchema": {
            "type": "object",
            "properties": {"path": {"type": "string"}, "proposal": {"type": "string"}},
            "required": ["path", "proposal"],
        },
    },
    "accept_apply_proposal": {
        "description": "Accept one draft native-project proposal and apply it through the generic proposal gateway.",
        "inputSchema": {
            "type": "object",
            "properties": {"path": {"type": "string"}, "proposal": {"type": "string"}},
            "required": ["path", "proposal"],
        },
    },
}
