use super::*;

pub(crate) fn execute_project_library_command(
    format: &OutputFormat,
    command: ProjectCommands,
) -> Result<(String, i32)> {
    match command {
        ProjectCommands::CreatePoolLibraryObject(ProjectCreatePoolLibraryObjectArgs {
            path,
            pool,
            kind,
            object_uuid,
            from_json,
        }) => Ok((
            render_output(
                format,
                &create_native_project_pool_library_object(
                    &path,
                    &pool,
                    &kind,
                    object_uuid,
                    &from_json,
                )?,
            ),
            0,
        )),
        ProjectCommands::DeletePoolLibraryObject(ProjectDeletePoolLibraryObjectArgs {
            path,
            pool,
            kind,
            object_uuid,
        }) => Ok((
            render_output(
                format,
                &delete_native_project_pool_library_object(&path, &pool, &kind, object_uuid)?,
            ),
            0,
        )),
        ProjectCommands::CreatePoolUnit(ProjectCreatePoolUnitArgs {
            path,
            pool,
            unit_uuid,
            name,
            manufacturer,
        }) => Ok((
            render_output(
                format,
                &create_native_project_pool_unit(&path, &pool, unit_uuid, name, manufacturer)?,
            ),
            0,
        )),
        ProjectCommands::SetPoolUnitPin(ProjectSetPoolUnitPinArgs {
            path,
            pool,
            unit_uuid,
            pin_uuid,
            name,
            direction,
            electrical_type,
            swap_group,
        }) => Ok((
            render_output(
                format,
                &set_native_project_pool_unit_pin(
                    &path,
                    &pool,
                    unit_uuid,
                    pin_uuid,
                    name,
                    direction,
                    electrical_type,
                    swap_group,
                )?,
            ),
            0,
        )),
        ProjectCommands::CreatePoolSymbol(ProjectCreatePoolSymbolArgs {
            path,
            pool,
            symbol_uuid,
            unit_uuid,
            name,
        }) => Ok((
            render_output(
                format,
                &create_native_project_pool_symbol(&path, &pool, symbol_uuid, unit_uuid, name)?,
            ),
            0,
        )),
        ProjectCommands::AddPoolSymbolLine(ProjectAddPoolSymbolLineArgs {
            path,
            pool,
            symbol_uuid,
            from_x_nm,
            from_y_nm,
            to_x_nm,
            to_y_nm,
            width_nm,
        }) => Ok((
            render_output(
                format,
                &add_native_project_pool_symbol_line(
                    &path,
                    &pool,
                    symbol_uuid,
                    from_x_nm,
                    from_y_nm,
                    to_x_nm,
                    to_y_nm,
                    width_nm,
                )?,
            ),
            0,
        )),
        ProjectCommands::AddPoolSymbolPolygon(ProjectAddPoolSymbolPolygonArgs {
            path,
            pool,
            symbol_uuid,
            vertices,
            closed,
            width_nm,
        }) => Ok((
            render_output(
                format,
                &add_native_project_pool_symbol_polygon(
                    &path,
                    &pool,
                    symbol_uuid,
                    &vertices,
                    closed,
                    width_nm,
                )?,
            ),
            0,
        )),
        ProjectCommands::AddPoolSymbolRect(ProjectAddPoolSymbolRectArgs {
            path,
            pool,
            symbol_uuid,
            min_x_nm,
            min_y_nm,
            max_x_nm,
            max_y_nm,
            width_nm,
        }) => Ok((
            render_output(
                format,
                &add_native_project_pool_symbol_rect(
                    &path,
                    &pool,
                    symbol_uuid,
                    min_x_nm,
                    min_y_nm,
                    max_x_nm,
                    max_y_nm,
                    width_nm,
                )?,
            ),
            0,
        )),
        ProjectCommands::AddPoolSymbolCircle(ProjectAddPoolSymbolCircleArgs {
            path,
            pool,
            symbol_uuid,
            center_x_nm,
            center_y_nm,
            radius_nm,
            width_nm,
        }) => Ok((
            render_output(
                format,
                &add_native_project_pool_symbol_circle(
                    &path,
                    &pool,
                    symbol_uuid,
                    center_x_nm,
                    center_y_nm,
                    radius_nm,
                    width_nm,
                )?,
            ),
            0,
        )),
        ProjectCommands::AddPoolSymbolArc(ProjectAddPoolSymbolArcArgs {
            path,
            pool,
            symbol_uuid,
            x_nm,
            y_nm,
            radius_nm,
            start_angle,
            end_angle,
            width_nm,
        }) => Ok((
            render_output(
                format,
                &add_native_project_pool_symbol_arc(
                    &path,
                    &pool,
                    symbol_uuid,
                    x_nm,
                    y_nm,
                    radius_nm,
                    start_angle,
                    end_angle,
                    width_nm,
                )?,
            ),
            0,
        )),
        ProjectCommands::AddPoolSymbolText(ProjectAddPoolSymbolTextArgs {
            path,
            pool,
            symbol_uuid,
            text,
            x_nm,
            y_nm,
            rotation,
        }) => Ok((
            render_output(
                format,
                &add_native_project_pool_symbol_text(
                    &path,
                    &pool,
                    symbol_uuid,
                    text,
                    x_nm,
                    y_nm,
                    rotation,
                )?,
            ),
            0,
        )),
        ProjectCommands::CreatePoolEntity(ProjectCreatePoolEntityArgs {
            path,
            pool,
            entity_uuid,
            gate_uuid,
            unit_uuid,
            symbol_uuid,
            name,
            prefix,
            manufacturer,
            gate_name,
        }) => Ok((
            render_output(
                format,
                &create_native_project_pool_entity(
                    &path,
                    &pool,
                    entity_uuid,
                    gate_uuid,
                    unit_uuid,
                    symbol_uuid,
                    name,
                    prefix,
                    manufacturer,
                    gate_name,
                )?,
            ),
            0,
        )),
        ProjectCommands::CreatePoolPadstack(ProjectCreatePoolPadstackArgs {
            path,
            pool,
            padstack_uuid,
            name,
            aperture,
            diameter_nm,
            width_nm,
            height_nm,
            drill_nm,
        }) => Ok((
            render_output(
                format,
                &create_native_project_pool_padstack(
                    &path,
                    &pool,
                    padstack_uuid,
                    name,
                    aperture,
                    diameter_nm,
                    width_nm,
                    height_nm,
                    drill_nm,
                )?,
            ),
            0,
        )),
        ProjectCommands::CreatePoolPackage(ProjectCreatePoolPackageArgs {
            path,
            pool,
            package_uuid,
            name,
            pad_uuid,
            padstack_uuid,
            pad_name,
            x_nm,
            y_nm,
            layer,
        }) => Ok((
            render_output(
                format,
                &create_native_project_pool_package(
                    &path,
                    &pool,
                    package_uuid,
                    name,
                    pad_uuid,
                    padstack_uuid,
                    pad_name,
                    x_nm,
                    y_nm,
                    layer,
                )?,
            ),
            0,
        )),
        ProjectCommands::SetPoolPackagePad(ProjectSetPoolPackagePadArgs {
            path,
            pool,
            package_uuid,
            pad_uuid,
            padstack_uuid,
            pad_name,
            x_nm,
            y_nm,
            layer,
        }) => Ok((
            render_output(
                format,
                &set_native_project_pool_package_pad(
                    &path,
                    &pool,
                    package_uuid,
                    pad_uuid,
                    padstack_uuid,
                    pad_name,
                    x_nm,
                    y_nm,
                    layer,
                )?,
            ),
            0,
        )),
        ProjectCommands::SetPoolPackageCourtyardRect(ProjectSetPoolPackageCourtyardRectArgs {
            path,
            pool,
            package_uuid,
            min_x_nm,
            min_y_nm,
            max_x_nm,
            max_y_nm,
        }) => Ok((
            render_output(
                format,
                &set_native_project_pool_package_courtyard_rect(
                    &path,
                    &pool,
                    package_uuid,
                    min_x_nm,
                    min_y_nm,
                    max_x_nm,
                    max_y_nm,
                )?,
            ),
            0,
        )),
        ProjectCommands::SetPoolPackageCourtyardPolygon(
            ProjectSetPoolPackageCourtyardPolygonArgs {
                path,
                pool,
                package_uuid,
                vertices,
            },
        ) => Ok((
            render_output(
                format,
                &set_native_project_pool_package_courtyard_polygon(
                    &path,
                    &pool,
                    package_uuid,
                    &vertices,
                )?,
            ),
            0,
        )),
        ProjectCommands::AddPoolPackageSilkscreenLine(
            ProjectAddPoolPackageSilkscreenLineArgs {
                path,
                pool,
                package_uuid,
                from_x_nm,
                from_y_nm,
                to_x_nm,
                to_y_nm,
                width_nm,
            },
        ) => Ok((
            render_output(
                format,
                &add_native_project_pool_package_silkscreen_line(
                    &path,
                    &pool,
                    package_uuid,
                    from_x_nm,
                    from_y_nm,
                    to_x_nm,
                    to_y_nm,
                    width_nm,
                )?,
            ),
            0,
        )),
        ProjectCommands::AddPoolPackageSilkscreenRect(
            ProjectAddPoolPackageSilkscreenRectArgs {
                path,
                pool,
                package_uuid,
                min_x_nm,
                min_y_nm,
                max_x_nm,
                max_y_nm,
                width_nm,
            },
        ) => Ok((
            render_output(
                format,
                &add_native_project_pool_package_silkscreen_rect(
                    &path,
                    &pool,
                    package_uuid,
                    min_x_nm,
                    min_y_nm,
                    max_x_nm,
                    max_y_nm,
                    width_nm,
                )?,
            ),
            0,
        )),
        ProjectCommands::AddPoolPackageSilkscreenCircle(
            ProjectAddPoolPackageSilkscreenCircleArgs {
                path,
                pool,
                package_uuid,
                center_x_nm,
                center_y_nm,
                radius_nm,
                width_nm,
            },
        ) => Ok((
            render_output(
                format,
                &add_native_project_pool_package_silkscreen_circle(
                    &path,
                    &pool,
                    package_uuid,
                    center_x_nm,
                    center_y_nm,
                    radius_nm,
                    width_nm,
                )?,
            ),
            0,
        )),
        ProjectCommands::AddPoolPackageSilkscreenArc(ProjectAddPoolPackageSilkscreenArcArgs {
            path,
            pool,
            package_uuid,
            x_nm,
            y_nm,
            radius_nm,
            start_angle,
            end_angle,
            width_nm,
        }) => Ok((
            render_output(
                format,
                &add_native_project_pool_package_silkscreen_arc(
                    &path,
                    &pool,
                    package_uuid,
                    x_nm,
                    y_nm,
                    radius_nm,
                    start_angle,
                    end_angle,
                    width_nm,
                )?,
            ),
            0,
        )),
        ProjectCommands::AddPoolPackageSilkscreenPolygon(
            ProjectAddPoolPackageSilkscreenPolygonArgs {
                path,
                pool,
                package_uuid,
                vertices,
                closed,
                width_nm,
            },
        ) => Ok((
            render_output(
                format,
                &add_native_project_pool_package_silkscreen_polygon(
                    &path,
                    &pool,
                    package_uuid,
                    &vertices,
                    closed,
                    width_nm,
                )?,
            ),
            0,
        )),
        ProjectCommands::AddPoolPackageSilkscreenText(
            ProjectAddPoolPackageSilkscreenTextArgs {
                path,
                pool,
                package_uuid,
                text,
                x_nm,
                y_nm,
                rotation,
            },
        ) => Ok((
            render_output(
                format,
                &add_native_project_pool_package_silkscreen_text(
                    &path,
                    &pool,
                    package_uuid,
                    text,
                    x_nm,
                    y_nm,
                    rotation,
                )?,
            ),
            0,
        )),
        ProjectCommands::AddPoolPackageModel3d(ProjectAddPoolPackageModel3dArgs {
            path,
            pool,
            package_uuid,
            model_path,
            format: model_format,
            transform_json,
            tx_nm,
            ty_nm,
            tz_nm,
            roll_tenths_deg,
            pitch_tenths_deg,
            yaw_tenths_deg,
            scale,
        }) => Ok((
            render_output(
                format,
                &add_native_project_pool_package_model_3d(
                    &path,
                    &pool,
                    package_uuid,
                    &model_path,
                    model_format,
                    transform_json.as_deref(),
                    tx_nm,
                    ty_nm,
                    tz_nm,
                    roll_tenths_deg,
                    pitch_tenths_deg,
                    yaw_tenths_deg,
                    scale.as_deref(),
                )?,
            ),
            0,
        )),
        ProjectCommands::SetPoolPackageBodyHeights(ProjectSetPoolPackageBodyHeightsArgs {
            path,
            pool,
            package_uuid,
            clear,
            body_height_nm,
            body_height_mounted_nm,
        }) => Ok((
            render_output(
                format,
                &set_native_project_pool_package_body_heights(
                    &path,
                    &pool,
                    package_uuid,
                    clear,
                    body_height_nm,
                    body_height_mounted_nm,
                )?,
            ),
            0,
        )),
        ProjectCommands::CreatePoolPart(ProjectCreatePoolPartArgs {
            path,
            pool,
            part_uuid,
            entity_uuid,
            package_uuid,
            mpn,
            manufacturer,
            value,
            description,
            datasheet,
            lifecycle,
        }) => Ok((
            render_output(
                format,
                &create_native_project_pool_part(
                    &path,
                    &pool,
                    part_uuid,
                    entity_uuid,
                    package_uuid,
                    mpn,
                    manufacturer,
                    value,
                    description,
                    datasheet,
                    lifecycle,
                )?,
            ),
            0,
        )),
        ProjectCommands::SetPoolPartMetadata(ProjectSetPoolPartMetadataArgs {
            path,
            pool,
            part_uuid,
            mpn,
            manufacturer,
            manufacturer_jep106,
            value,
            description,
            datasheet,
            lifecycle,
        }) => Ok((
            render_output(
                format,
                &set_native_project_pool_part_metadata(
                    &path,
                    &pool,
                    part_uuid,
                    mpn,
                    manufacturer,
                    manufacturer_jep106,
                    value,
                    description,
                    datasheet,
                    lifecycle,
                )?,
            ),
            0,
        )),
        ProjectCommands::SetPoolPartParametric(ProjectSetPoolPartParametricArgs {
            path,
            pool,
            part_uuid,
            mode,
            params,
        }) => Ok((
            render_output(
                format,
                &set_native_project_pool_part_parametric(&path, &pool, part_uuid, mode, params)?,
            ),
            0,
        )),
        ProjectCommands::SetPoolPartOrderableMpns(ProjectSetPoolPartOrderableMpnsArgs {
            path,
            pool,
            part_uuid,
            mode,
            mpns,
        }) => Ok((
            render_output(
                format,
                &set_native_project_pool_part_orderable_mpns(&path, &pool, part_uuid, mode, mpns)?,
            ),
            0,
        )),
        ProjectCommands::SetPoolPartPackagingOptions(ProjectSetPoolPartPackagingOptionsArgs {
            path,
            pool,
            part_uuid,
            mode,
            options,
        }) => Ok((
            render_output(
                format,
                &set_native_project_pool_part_packaging_options(
                    &path, &pool, part_uuid, mode, options,
                )?,
            ),
            0,
        )),
        ProjectCommands::SetPoolPartBehaviouralModels(
            ProjectSetPoolPartBehaviouralModelsArgs {
                path,
                pool,
                part_uuid,
                mode,
                models,
            },
        ) => Ok((
            render_output(
                format,
                &set_native_project_pool_part_behavioural_models(
                    &path, &pool, part_uuid, mode, models,
                )?,
            ),
            0,
        )),
        ProjectCommands::AttachPoolPartModel(ProjectAttachPoolPartModelArgs {
            path,
            pool,
            part_uuid,
            source,
            role,
            dialect,
            model_names,
            encrypted,
            encryption_scheme,
            vendor,
            fetched_at,
            format_metadata_json,
        }) => Ok((
            render_output(
                format,
                &attach_native_project_pool_part_model(
                    &path,
                    &pool,
                    part_uuid,
                    &source,
                    role,
                    dialect,
                    model_names,
                    encrypted,
                    encryption_scheme,
                    vendor,
                    fetched_at,
                    format_metadata_json,
                )?,
            ),
            0,
        )),
        ProjectCommands::DetachPoolPartModel(ProjectDetachPoolPartModelArgs {
            path,
            pool,
            part_uuid,
            attachment_uuid,
            model_uuid,
        }) => Ok((
            render_output(
                format,
                &detach_native_project_pool_part_model(
                    &path,
                    &pool,
                    part_uuid,
                    attachment_uuid,
                    model_uuid,
                )?,
            ),
            0,
        )),
        ProjectCommands::GcPoolModels(ProjectGcPoolModelsArgs {
            path,
            pool,
            role,
            sha256,
            apply,
        }) => Ok((
            render_output(
                format,
                &gc_native_project_pool_models(
                    &path,
                    &pool,
                    role.as_deref(),
                    sha256.as_deref(),
                    apply,
                )?,
            ),
            0,
        )),
        ProjectCommands::SetPoolPartThermal(ProjectSetPoolPartThermalArgs {
            path,
            pool,
            part_uuid,
            clear,
            theta_ja_c_per_w,
            theta_jc_top_c_per_w,
            theta_jc_bot_c_per_w,
            theta_jb_c_per_w,
            max_junction_c,
            thermal_reference,
        }) => Ok((
            render_output(
                format,
                &set_native_project_pool_part_thermal(
                    &path,
                    &pool,
                    part_uuid,
                    clear,
                    theta_ja_c_per_w,
                    theta_jc_top_c_per_w,
                    theta_jc_bot_c_per_w,
                    theta_jb_c_per_w,
                    max_junction_c,
                    thermal_reference,
                )?,
            ),
            0,
        )),
        ProjectCommands::SetPoolPartSupplyChain(ProjectSetPoolPartSupplyChainArgs {
            path,
            pool,
            part_uuid,
            clear,
            checked_at,
            offers,
        }) => Ok((
            render_output(
                format,
                &set_native_project_pool_part_supply_chain(
                    &path, &pool, part_uuid, clear, checked_at, offers,
                )?,
            ),
            0,
        )),
        ProjectCommands::SetPoolPartTags(ProjectSetPoolPartTagsArgs {
            path,
            pool,
            part_uuid,
            mode,
            tags,
        }) => Ok((
            render_output(
                format,
                &set_native_project_pool_part_tags(&path, &pool, part_uuid, mode, tags)?,
            ),
            0,
        )),
        ProjectCommands::SetPoolPartPadMap(ProjectSetPoolPartPadMapArgs {
            path,
            pool,
            part_uuid,
            mode,
            entries,
        }) => Ok((
            render_output(
                format,
                &set_native_project_pool_part_pad_map_from_entries(
                    &path, &pool, part_uuid, mode, entries,
                )?,
            ),
            0,
        )),
        ProjectCommands::SetPoolPartPadMapEntry(ProjectSetPoolPartPadMapEntryArgs {
            path,
            pool,
            part_uuid,
            pad_uuid,
            gate_uuid,
            pin_uuid,
        }) => Ok((
            render_output(
                format,
                &set_native_project_pool_part_pad_map_entry(
                    &path, &pool, part_uuid, pad_uuid, gate_uuid, pin_uuid,
                )?,
            ),
            0,
        )),
        ProjectCommands::SetPoolLibraryObject(ProjectSetPoolLibraryObjectArgs {
            path,
            pool,
            kind,
            object_uuid,
            from_json,
        }) => Ok((
            render_output(
                format,
                &set_native_project_pool_library_object(
                    &path,
                    &pool,
                    &kind,
                    object_uuid,
                    &from_json,
                )?,
            ),
            0,
        )),
        _ => unreachable!("project library dispatcher received non-library command"),
    }
}
