#!/usr/bin/env python3
"""Generate compact Datum TerminalCore Unicode 17 property tables offline."""

from __future__ import annotations

import argparse
import hashlib
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "crates/terminal-core/unicode/17.0.0"
OUTPUT = ROOT / "crates/terminal-core/src"
EXPECTED_SHA256 = {
    "DerivedCoreProperties.txt": "24c7fed1195c482faaefd5c1e7eb821c5ee1fb6de07ecdbaa64b56a99da22c08",
    "EastAsianWidth.txt": "ea7ce50f3444a050333448dffef1cadd9325af55cbb764b4a2280faf52170a33",
    "GraphemeBreakProperty.txt": "d6b51d1d2ae5c33b451b7ed994b48f1f4dc62b2272a5831e7fd418514a6bae89",
    "GraphemeBreakTest.txt": "e2d134d2c52919bace503ebb6a551c1855fe1a1faec18478c78fff254a1793ec",
    "emoji-data.txt": "2cb2bb9455cda83e8481541ecf5b6dfda66a3bb89efa3fa7c5297eccf607b72b",
    "emoji-sequences.txt": "12cc8267dc33cbd11ed32bcf6fc5dc2ad9c7a77bae1bdfba2f41b1b9b3ead8dd",
    "emoji-variation-sequences.txt": "bb3d09ef03f206012c7532dd52dc0a21c9efddba0135ea4cf0d9201b8b9bba7e",
    "emoji-zwj-sequences.txt": "5b25441daed2322b068c5e70cda522946a4f0274df864445a1965a92e5fc5cad",
    "../LICENSE.txt": "e7a93b009565cfce55919a381437ac4db883e9da2126fa28b91d12732bc53d96",
}


Range = tuple[int, int, str]


def verify_inputs() -> None:
    for name, expected in EXPECTED_SHA256.items():
        path = DATA / name
        actual = hashlib.sha256(path.read_bytes()).hexdigest()
        if actual != expected:
            raise SystemExit(f"{name}: expected {expected}, found {actual}")


def code_range(field: str) -> tuple[int, int]:
    values = field.strip().split("..")
    start = int(values[0], 16)
    return start, int(values[-1], 16)


def merge(ranges: list[Range]) -> list[Range]:
    ranges.sort(key=lambda item: (item[0], item[1], item[2]))
    merged: list[Range] = []
    for start, end, value in ranges:
        if merged and merged[-1][2] == value and merged[-1][1] + 1 == start:
            prior = merged[-1]
            merged[-1] = (prior[0], end, value)
        else:
            merged.append((start, end, value))
    return merged


def parse_simple(path: Path, properties: set[str]) -> list[Range]:
    ranges: list[Range] = []
    for raw in path.read_text(encoding="utf-8").splitlines():
        body = raw.split("#", 1)[0].strip()
        if not body:
            continue
        fields = [field.strip() for field in body.split(";")]
        if len(fields) < 2 or fields[1] not in properties:
            continue
        start, end = code_range(fields[0])
        ranges.append((start, end, fields[1]))
    return merge(ranges)


def parse_incb(path: Path) -> list[Range]:
    ranges: list[Range] = []
    for raw in path.read_text(encoding="utf-8").splitlines():
        body = raw.split("#", 1)[0].strip()
        fields = [field.strip() for field in body.split(";")]
        if len(fields) < 3 or fields[1] != "InCB" or fields[2] == "None":
            continue
        start, end = code_range(fields[0])
        ranges.append((start, end, fields[2]))
    return merge(ranges)


def rust_name(value: str) -> str:
    return {
        "Regional_Indicator": "RegionalIndicator",
        "ZWJ": "Zwj",
        "LVT": "Lvt",
        "SpacingMark": "SpacingMark",
        "Extended_Pictographic": "ExtendedPictographic",
        "Emoji_Presentation": "EmojiPresentation",
    }.get(value, value)


def render_array(name: str, kind: str, ranges: list[Range]) -> str:
    entries = [
        f"(0x{start:X}, 0x{end:X}, {kind}::{rust_name(value)})"
        for start, end, value in ranges
    ]
    lines = ["#[rustfmt::skip]", f"pub(crate) const {name}: &[Range<{kind}>] = &["]
    for index in range(0, len(entries), 3):
        lines.append("    " + ", ".join(entries[index : index + 3]) + ",")
    lines.append("];\n")
    return "\n".join(lines)


def header(source_names: str, imports: str) -> str:
    return (
        "// @generated by scripts/generate_terminal_unicode.py; do not hand edit.\n"
        "// Unicode 17.0.0; inputs: " + source_names + ".\n\n"
        f"use crate::unicode::{{{imports}, Range}};\n\n"
    )


def generated_files() -> dict[Path, str]:
    grapheme = parse_simple(
        DATA / "GraphemeBreakProperty.txt",
        {
            "CR", "LF", "Control", "Extend", "ZWJ", "Regional_Indicator",
            "Prepend", "SpacingMark", "L", "V", "T", "LV", "LVT",
        },
    )
    incb = parse_incb(DATA / "DerivedCoreProperties.txt")
    width = parse_simple(DATA / "EastAsianWidth.txt", {"W", "F", "A"})
    extended_pictographic = parse_simple(
        DATA / "emoji-data.txt", {"Extended_Pictographic"}
    )
    emoji_presentation = parse_simple(DATA / "emoji-data.txt", {"Emoji_Presentation"})
    grapheme_text = header(
        "GraphemeBreakProperty.txt, DerivedCoreProperties.txt",
        "GraphemeBreak, IndicConjunctBreak",
    )
    grapheme_text += render_array("GRAPHEME_BREAK_RANGES", "GraphemeBreak", grapheme)
    grapheme_text += render_array("INCB_RANGES", "IndicConjunctBreak", incb)
    width_text = header(
        "EastAsianWidth.txt, emoji-data.txt", "EastAsianWidth, EmojiProperty"
    )
    width_text += render_array("EAST_ASIAN_WIDTH_RANGES", "EastAsianWidth", width)
    width_text += render_array(
        "EXTENDED_PICTOGRAPHIC_RANGES", "EmojiProperty", extended_pictographic
    )
    width_text += render_array(
        "EMOJI_PRESENTATION_RANGES", "EmojiProperty", emoji_presentation
    )
    return {
        OUTPUT / "unicode_grapheme_tables.rs": grapheme_text,
        OUTPUT / "unicode_width_tables.rs": width_text,
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    arguments = parser.parse_args()
    verify_inputs()
    failures: list[str] = []
    for path, generated in generated_files().items():
        if arguments.check:
            if not path.is_file() or path.read_text(encoding="utf-8") != generated:
                failures.append(str(path.relative_to(ROOT)))
        else:
            path.write_text(generated, encoding="utf-8")
    if failures:
        raise SystemExit("stale generated Unicode tables: " + ", ".join(failures))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
