use super::*;

pub(super) fn descriptors() -> Vec<PreferenceDescriptor> {
    use ApplyBehavior::{
        Live, LiveAfterWholeValueValidation, LiveWithBoundedTrim, NewProjectOnly,
        NextApplicationLaunch, NextTerminalLaunch, PrefillOnly,
    };
    use AuthorityReleaseLevel::{BacksideManagement, FullManagement};
    use ExportClass::{Portable, Protected};
    use SettingClass::{Capability, Presentation, ProjectPolicySeed, WorkflowDefault};

    vec![
        descriptor(
            "datum.pcb.airwires_hidden_layers",
            "PCB presentation",
            "enum {visible_layers,all_layers}",
            enum_schema(&["visible_layers", "all_layers"]),
            literal(json!("visible_layers")),
            Presentation,
            usc(true),
            rc(),
            Live,
            &["airwire renderer"],
            Portable,
            "Airwires on hidden layers",
            "Controls whether hidden-layer endpoints retain visible airwires.",
            &[],
        ),
        descriptor(
            "datum.pcb.viewport_airwire_culling",
            "PCB presentation",
            "bool",
            ValueSchema::Boolean,
            literal(json!(false)),
            Presentation,
            usc(true),
            rc(),
            Live,
            &["airwire renderer", "board rendering performance"],
            Portable,
            "Viewport airwire culling",
            "Limits airwire drawing to connections with an endpoint in the viewport.",
            &[],
        ),
        descriptor(
            "datum.checks.profile_prefill",
            "checks engine",
            "enum {full,fast,last_used}",
            enum_schema(&["full", "fast", "last_used"]),
            literal(json!("last_used")),
            WorkflowDefault,
            usc(true),
            rcpl(BacksideManagement),
            PrefillOnly,
            &["run_check"],
            Portable,
            "Check profile pre-fill",
            "Pre-fills run_check while preserving its explicit profile parameter.",
            &[],
        ),
        descriptor(
            "datum.publish.title_block_template_seed",
            "documentation",
            "resolvable template-set identity",
            ValueSchema::Identity { nullable: false },
            literal(json!("datum_factory")),
            ProjectPolicySeed,
            seed(),
            rcpl(BacksideManagement),
            NewProjectOnly,
            &["ProjectDocumentTemplates"],
            Portable,
            "Title-block / sheet template seed",
            "Copies the selected title-block and sheet-template set into a new Project.",
            &[],
        ),
        descriptor(
            "datum.publish.sheet_format_seed",
            "documentation",
            "struct {size,orientation}",
            ValueSchema::Semantic(SemanticSchema::SheetFormat),
            literal(json!({"size":"A3","orientation":"landscape"})),
            ProjectPolicySeed,
            seed(),
            rcpl(BacksideManagement),
            NewProjectOnly,
            &["ProjectDocumentTemplates"],
            Portable,
            "Default sheet size and orientation",
            "Copies the starting publish-sheet format into a new Project.",
            &[],
        ),
        descriptor(
            "datum.publish.scale_fraction_style_seed",
            "documentation",
            "enum {one_to_n,n_over_one,custom_pattern}",
            enum_schema(&["one_to_n", "n_over_one", "custom_pattern"]),
            literal(json!("one_to_n")),
            ProjectPolicySeed,
            seed(),
            rcpl(BacksideManagement),
            NewProjectOnly,
            &["AdoptedDraftingStandard"],
            Portable,
            "Title-block scale fraction style",
            "Copies the scale-fraction presentation convention into a new Project.",
            &[],
        ),
        descriptor(
            "datum.publish.viewport_creation_prefill",
            "documentation",
            "enum {on_demand,on_demand_remember_style}",
            enum_schema(&["on_demand", "on_demand_remember_style"]),
            literal(json!("on_demand")),
            WorkflowDefault,
            usc(true),
            rcpl(BacksideManagement),
            PrefillOnly,
            &["publish viewport creation"],
            Portable,
            "Viewport creation",
            "Pre-fills on-demand viewport creation without removing the explicit operation choice.",
            &[],
        ),
        descriptor(
            "datum.publish.publish_set_naming",
            "documentation",
            "struct {mode,pattern}",
            ValueSchema::Semantic(SemanticSchema::PublishSetNaming),
            literal(json!({"mode":"pattern","pattern":"{project}-{set}"})),
            WorkflowDefault,
            usc(true),
            rcpl(BacksideManagement),
            PrefillOnly,
            &["publish-set creation"],
            Portable,
            "Publish-set naming pre-fill",
            "Suggests a publish-set name while preserving the explicit name request.",
            &["datum.publish.set_name_prefill"],
        ),
        descriptor(
            "datum.terminal.launch_profiles",
            "terminal session",
            "versioned named launch-profile list",
            ValueSchema::Semantic(SemanticSchema::TerminalLaunchProfiles),
            runtime("platform.default_shell_profile.v1"),
            Capability,
            us(true),
            rcpl(BacksideManagement),
            NextTerminalLaunch,
            &["PTY session launcher"],
            Protected,
            "Terminal launch profiles",
            "Defines validated terminal launch templates without allowing Project executable control.",
            &[],
        ),
        descriptor(
            "datum.terminal.theme",
            "terminal presentation",
            "enum {datum_dark,high_contrast}",
            enum_schema(&["datum_dark", "high_contrast"]),
            literal(json!("datum_dark")),
            Presentation,
            us(true),
            rc(),
            Live,
            &["terminal renderer"],
            Portable,
            "Terminal theme and palette",
            "Selects the terminal color theme and palette.",
            &[],
        ),
        descriptor(
            "datum.terminal.text_rendering",
            "terminal presentation",
            "struct {zoom:60..200 step10,ligatures:bool}",
            ValueSchema::Semantic(SemanticSchema::TerminalTextRendering),
            literal(json!({"zoom":100,"ligatures":false})),
            Presentation,
            us(true),
            rc(),
            Live,
            &["terminal renderer"],
            Portable,
            "Terminal font size and ligatures",
            "Controls terminal zoom and ligatures while preserving the pinned cell typeface.",
            &[],
        ),
        descriptor(
            "datum.terminal.cursor",
            "terminal presentation",
            "struct {shape,blink}",
            ValueSchema::Semantic(SemanticSchema::TerminalCursor),
            literal(json!({"shape":"block","blink":true})),
            Presentation,
            us(true),
            rc(),
            Live,
            &["terminal renderer"],
            Portable,
            "Terminal cursor style",
            "Selects terminal cursor shape and blink behavior.",
            &[],
        ),
        descriptor(
            "datum.terminal.feedback",
            "terminal presentation",
            "struct {bell,activity,copy_confirmation}",
            ValueSchema::Semantic(SemanticSchema::TerminalFeedback),
            literal(json!({"bell":"visual","activity":true,"copy_confirmation":false})),
            Presentation,
            us(true),
            rc(),
            Live,
            &["terminal", "desktop shell"],
            Portable,
            "Terminal bell, activity, and copy feedback",
            "Controls terminal bell, activity indication, and copy confirmation.",
            &["terminal.legacy_bell_mode"],
        ),
        descriptor(
            "datum.terminal.scrollback",
            "terminal resource policy",
            "struct {max_lines:100..100000,max_mib:1..64}",
            ValueSchema::Semantic(SemanticSchema::TerminalScrollback),
            literal(json!({"max_lines":50000,"max_mib":64})),
            Capability,
            us(true),
            rcpl(BacksideManagement),
            LiveWithBoundedTrim,
            &["terminal VT state"],
            Protected,
            "Terminal scrollback limits",
            "Bounds terminal scrollback by both line count and memory.",
            &[],
        ),
        descriptor(
            "datum.terminal.notifications",
            "terminal capability",
            "enum {off,unfocused,always}",
            enum_schema(&["off", "unfocused", "always"]),
            literal(json!("unfocused")),
            Capability,
            us(true),
            rcpl(BacksideManagement),
            Live,
            &["desktop notification adapter"],
            Protected,
            "Terminal desktop notifications",
            "Controls when terminal activity may create desktop notifications.",
            &[],
        ),
        descriptor(
            "datum.terminal.keymap",
            "terminal input",
            "versioned action-to-gesture map",
            ValueSchema::Semantic(SemanticSchema::VersionedKeymap),
            runtime("terminal.keymap.datum_v1"),
            WorkflowDefault,
            us(true),
            rcpl(FullManagement),
            LiveAfterWholeValueValidation,
            &["terminal dispatcher"],
            Portable,
            "Terminal key bindings",
            "Maps terminal action identities to validated gestures.",
            &[],
        ),
        descriptor(
            "datum.terminal.multiline_paste",
            "terminal security",
            "enum {ask,allow,block}",
            enum_schema(&["ask", "allow", "block"]),
            literal(json!("ask")),
            Capability,
            us(true),
            rcpl(BacksideManagement),
            Live,
            &["terminal paste gate"],
            Protected,
            "Multiline paste policy",
            "Controls confirmation or refusal for multiline terminal paste.",
            &[],
        ),
        descriptor(
            "datum.terminal.osc52_write",
            "terminal security",
            "enum {ask,allow,block}",
            enum_schema(&["ask", "allow", "block"]),
            literal(json!("ask")),
            Capability,
            us(true),
            rcpl(BacksideManagement),
            Live,
            &["OSC 52 gate"],
            Protected,
            "OSC 52 clipboard write gating",
            "Controls whether terminal applications may write the system clipboard.",
            &[],
        ),
        descriptor(
            "datum.terminal.open_target_policy",
            "terminal security",
            "enum {ask,trusted_only,never}",
            enum_schema(&["ask", "trusted_only", "never"]),
            literal(json!("ask")),
            Capability,
            us(true),
            rcpl(BacksideManagement),
            Live,
            &["hyperlink and file opener"],
            Protected,
            "Hyperlink and file-open trust policy",
            "Controls confirmation before opening terminal-provided targets.",
            &[],
        ),
        descriptor(
            "datum.projects.startup_view",
            "application shell",
            "enum {start_page,last_session,empty}",
            enum_schema(&["start_page", "last_session", "empty"]),
            literal(json!("start_page")),
            WorkflowDefault,
            us(true),
            rcpl(FullManagement),
            NextApplicationLaunch,
            &["application shell", "start page"],
            Portable,
            "Startup and recent files",
            "Selects the application startup view without converting recent history into a preference.",
            &["datum.files.startup_mode"],
        ),
        descriptor(
            "datum.files.default_locations",
            "file services",
            "typed platform-path map",
            ValueSchema::Semantic(SemanticSchema::DefaultLocations),
            runtime("platform.documents_datum_locations.v1"),
            WorkflowDefault,
            us(true),
            rcpl(FullManagement),
            PrefillOnly,
            &["file pickers"],
            Portable,
            "Default file locations",
            "Pre-fills project, library, output-job, and new-project locations.",
            &[],
        ),
        descriptor(
            "datum.files.autosave",
            "document persistence",
            "struct {interval,retained_versions,backup_age,recovery,reminder}",
            ValueSchema::Semantic(SemanticSchema::AutosavePolicy),
            runtime("document_persistence.autosave_defaults.v1"),
            WorkflowDefault,
            usc(true),
            rcpl(BacksideManagement),
            Live,
            &["document persistence"],
            Portable,
            "Auto-save, backup, and recovery",
            "Controls auto-save scheduling, retained backups, recovery snapshots, and reminders.",
            &[],
        ),
        descriptor(
            "datum.projects.seed_profile",
            "Project genesis",
            "resolvable profile identity",
            ValueSchema::Identity { nullable: false },
            literal(json!("datum_factory")),
            ProjectPolicySeed,
            seed(),
            rcpl(BacksideManagement),
            NewProjectOnly,
            &["ProjectSeedSnapshot"],
            Portable,
            "New-Project seed profile selection",
            "Copies one resolved immutable seed snapshot into a new Project with a receipt.",
            &[],
        ),
        descriptor(
            "datum.projects.template_set",
            "Project genesis",
            "resolvable template identity or none",
            ValueSchema::Identity { nullable: true },
            literal(json!("datum_starter")),
            ProjectPolicySeed,
            seed(),
            rcpl(BacksideManagement),
            NewProjectOnly,
            &["ProjectTemplateCopy"],
            Portable,
            "New-project templates",
            "Copies the selected template set into a new Project.",
            &["datum.projects.template_seed"],
        ),
        descriptor(
            "datum.projects.unit_policy_seed",
            "Project genesis/units",
            "optional ProjectDisplayUnits aggregate",
            ValueSchema::Semantic(SemanticSchema::ProjectDisplayUnits),
            DescriptorDefault::Absent,
            ProjectPolicySeed,
            seed(),
            rcpl(BacksideManagement),
            NewProjectOnly,
            &["ProjectDisplayUnits"],
            Portable,
            "Default unit system for new projects",
            "Optionally copies an explicit unit-policy aggregate into a new Project.",
            &[],
        ),
        descriptor(
            "datum.output.job_prefill",
            "output orchestration",
            "enum {ask,last_used}",
            enum_schema(&["ask", "last_used"]),
            literal(json!("ask")),
            WorkflowDefault,
            usc(true),
            rcpl(BacksideManagement),
            PrefillOnly,
            &["Generate"],
            Portable,
            "Default output job pre-fill",
            "Pre-fills Generate while keeping the output job an explicit Project fact.",
            &[],
        ),
        descriptor(
            "datum.output.destination_prefill",
            "output orchestration",
            "enum {ask,project_outputs}",
            enum_schema(&["ask", "project_outputs"]),
            literal(json!("ask")),
            WorkflowDefault,
            usc(true),
            rcpl(BacksideManagement),
            PrefillOnly,
            &["export"],
            Portable,
            "Export destination pre-fill",
            "Pre-fills an export destination while preserving the per-run choice.",
            &[],
        ),
    ]
}
