use super::*;

pub(super) fn descriptors() -> Vec<PreferenceDescriptor> {
    use ApplyBehavior::{Live, LiveAfterWholeValueValidation, LiveAndNewProjectSeed, PrefillOnly};
    use AuthorityReleaseLevel::{BacksideManagement, FullManagement};
    use ExportClass::Portable;
    use SettingClass::{Presentation, ProjectPolicySeed, WorkflowDefault};

    vec![
        descriptor(
            "datum.console.feedback_duration",
            "GUI shell",
            "enum {4s,6s,10s,never}",
            enum_schema(&["4s", "6s", "10s", "never"]),
            literal(json!("6s")),
            Presentation,
            us(true),
            rc(),
            Live,
            &["Console feedback timer"],
            Portable,
            "Console feedback duration",
            "How long Console feedback stays visible before auto-hiding.",
            &["console_duration"],
        ),
        descriptor(
            "datum.accessibility.reduced_motion",
            "GUI accessibility",
            "bool",
            ValueSchema::Boolean,
            literal(json!(false)),
            Presentation,
            us(false),
            vec![],
            Live,
            &["all GUI animation", "terminal animation"],
            Portable,
            "Reduced motion",
            "Disables non-essential interface animation while preserving non-color state cues.",
            &[],
        ),
        descriptor(
            "datum.accessibility.high_contrast_noncolor",
            "GUI accessibility",
            "bool",
            ValueSchema::Boolean,
            literal(json!(false)),
            Presentation,
            us(false),
            vec![],
            Live,
            &["GUI renderer", "terminal renderer"],
            Portable,
            "High contrast and non-color cues",
            "Uses high-contrast rendering with non-color state cues across GUI and terminal.",
            &[],
        ),
        descriptor(
            "datum.pcb.layer_color_scheme",
            "PCB presentation",
            "enum {datum,high_contrast_mono,photonics}",
            enum_schema(&["datum", "high_contrast_mono", "photonics"]),
            literal(json!("datum")),
            Presentation,
            usc(true),
            rc(),
            Live,
            &["board renderer"],
            Portable,
            "Layer color scheme",
            "Selects the board layer color theme without changing design truth.",
            &[],
        ),
        descriptor(
            "datum.schematic.drawing_theme",
            "schematic presentation",
            "enum {dark,light}",
            enum_schema(&["dark", "light"]),
            literal(json!("dark")),
            Presentation,
            us(true),
            rc(),
            Live,
            &["schematic canvas"],
            Portable,
            "Schematic drawing theme",
            "Selects the complete schematic contrast system; print output is unaffected.",
            &["datum.schematic.theme"],
        ),
        descriptor(
            "datum.pcb.object_opacity",
            "PCB presentation",
            "struct {track,via,pad,zone:u8 0..100}",
            ValueSchema::Semantic(SemanticSchema::ObjectOpacity),
            literal(json!({"track":100,"via":100,"pad":100,"zone":70})),
            Presentation,
            usc(true),
            rc(),
            Live,
            &["board renderer"],
            Portable,
            "Per-object opacity",
            "Sets independent presentation opacity for tracks, vias, pads, and zones.",
            &[],
        ),
        descriptor(
            "datum.pcb.inactive_layer_dim_percent",
            "PCB presentation",
            "integer 0..100",
            ValueSchema::IntegerRange {
                min: 0,
                max: 100,
                step: 1,
            },
            literal(json!(50)),
            Presentation,
            usc(true),
            rc(),
            Live,
            &["board renderer"],
            Portable,
            "Inactive-layer dim factor",
            "Controls how much inactive layers dim in high-contrast layer mode.",
            &[],
        ),
        descriptor(
            "datum.pcb.pad_outline_mode",
            "PCB presentation",
            "bool",
            ValueSchema::Boolean,
            literal(json!(false)),
            Presentation,
            usc(true),
            rc(),
            Live,
            &["board renderer"],
            Portable,
            "Pad outline mode",
            "Renders pads as outlines for high-contrast placement review.",
            &[],
        ),
        descriptor(
            "datum.pcb.ghost_via_through_pad",
            "PCB presentation",
            "bool",
            ValueSchema::Boolean,
            literal(json!(false)),
            Presentation,
            usc(true),
            rc(),
            Live,
            &["board renderer"],
            Portable,
            "Ghost via through pad",
            "Shows vias ghosted through pads during placement review.",
            &[],
        ),
        descriptor(
            "datum.pcb.rounded_track_corners",
            "PCB presentation",
            "bool",
            ValueSchema::Boolean,
            literal(json!(false)),
            Presentation,
            usc(true),
            rc(),
            Live,
            &["board renderer"],
            Portable,
            "Rounded track corners",
            "Draws track corners rounded instead of mitred.",
            &[],
        ),
        descriptor(
            "datum.viewport.snap_enabled",
            "shared viewport",
            "bool",
            ValueSchema::Boolean,
            literal(json!(true)),
            WorkflowDefault,
            usc(true),
            rcpl(FullManagement),
            Live,
            &["schematic editor", "PCB editor"],
            Portable,
            "Grid snap on/off",
            "Controls whether authoring gestures snap to the active grid.",
            &[],
        ),
        descriptor(
            "datum.viewport.snap_capture_px",
            "shared viewport",
            "integer 1..64",
            ValueSchema::IntegerRange {
                min: 1,
                max: 64,
                step: 1,
            },
            literal(json!(10)),
            WorkflowDefault,
            usc(true),
            rcpl(FullManagement),
            Live,
            &["snap resolver"],
            Portable,
            "Snap capture radius",
            "Sets the screen-pixel radius within which an object snap engages.",
            &[],
        ),
        descriptor(
            "datum.viewport.fine_grid_divisor",
            "shared viewport",
            "enum {2,5,10}",
            enum_schema(&["2", "5", "10"]),
            literal(json!("10")),
            WorkflowDefault,
            usc(true),
            rcpl(FullManagement),
            Live,
            &["grid resolver"],
            Portable,
            "Fine-grid divisor",
            "Sets the temporary fine-grid subdivision used by the fine-grid modifier.",
            &[],
        ),
        descriptor(
            "datum.viewport.object_snap_types",
            "shared viewport",
            "typed SnapTargetKind set",
            ValueSchema::Semantic(SemanticSchema::ObjectSnapTypes),
            literal(
                json!({"types":["pad_center","via_center","track_endpoint","track_vertex","junction","pad_on_grid","pin_endpoint","wire_endpoint","wire_vertex","bus_connection","label_anchor","no_connect"],"current_layer_only":false}),
            ),
            WorkflowDefault,
            usc(true),
            rcpl(FullManagement),
            Live,
            &["snap resolver"],
            Portable,
            "Object snap types",
            "Selects eligible typed object snaps and the current-layer-only gate.",
            &[],
        ),
        descriptor(
            "datum.viewport.grid_mark_style",
            "shared viewport",
            "struct {shape:cross|dot|line,size:u8,min_spacing_px:u8}",
            ValueSchema::Semantic(SemanticSchema::GridMarkStyle),
            runtime("shared_viewport.grid_mark_style.v1"),
            Presentation,
            usc(true),
            rc(),
            Live,
            &["grid renderer"],
            Portable,
            "Grid mark style",
            "Controls grid mark shape, mark size, and minimum visible spacing.",
            &[],
        ),
        descriptor(
            "datum.input.editor_keymap",
            "input authority",
            "versioned action-to-gesture map",
            ValueSchema::Semantic(SemanticSchema::VersionedKeymap),
            runtime("input.editor_keymap.datum_v1"),
            WorkflowDefault,
            usc(true),
            rcpl(FullManagement),
            LiveAfterWholeValueValidation,
            &["editor dispatcher"],
            Portable,
            "Keyboard bindings (keymap)",
            "Maps editor action identities to validated non-exclusive gestures.",
            &[],
        ),
        descriptor(
            "datum.units.system",
            "units engine",
            "enum {metric,imperial}",
            enum_schema(&["metric", "imperial"]),
            literal(json!("metric")),
            ProjectPolicySeed,
            seed(),
            rcpl(BacksideManagement),
            LiveAndNewProjectSeed,
            &["ProjectDisplayUnits", "display formatter", "input parser"],
            Portable,
            "Measurement system",
            "Selects the default display system while exact authored values remain nanometers.",
            &[],
        ),
        descriptor(
            "datum.units.board_length",
            "units engine",
            "enum {follow_system,mm,um,mil,inch}",
            enum_schema(&["follow_system", "mm", "um", "mil", "inch"]),
            literal(json!("follow_system")),
            ProjectPolicySeed,
            seed(),
            rcpl(BacksideManagement),
            LiveAndNewProjectSeed,
            &["ProjectDisplayUnits", "display formatter", "input parser"],
            Portable,
            "Board and layout lengths",
            "Selects the display unit for board and layout length quantities.",
            &[],
        ),
        descriptor(
            "datum.units.drill_hole",
            "units engine",
            "enum {follow_system,mm,mil,inch}",
            enum_schema(&["follow_system", "mm", "mil", "inch"]),
            literal(json!("follow_system")),
            ProjectPolicySeed,
            seed(),
            rcpl(BacksideManagement),
            LiveAndNewProjectSeed,
            &["ProjectDisplayUnits", "display formatter", "input parser"],
            Portable,
            "Drill and hole sizes",
            "Selects the display unit for drill and hole quantities.",
            &[],
        ),
        descriptor(
            "datum.units.schematic_geometry",
            "units engine",
            "enum {follow_system,mm,mil}",
            enum_schema(&["follow_system", "mm", "mil"]),
            literal(json!("follow_system")),
            ProjectPolicySeed,
            seed(),
            rcpl(BacksideManagement),
            LiveAndNewProjectSeed,
            &["ProjectDisplayUnits", "display formatter", "input parser"],
            Portable,
            "Schematic geometry",
            "Selects the display unit for schematic geometry quantities.",
            &[],
        ),
        descriptor(
            "datum.units.length_precision",
            "units engine",
            "enum {0.1,0.01,0.001,0.0001,exact_nm}",
            enum_schema(&["0.1", "0.01", "0.001", "0.0001", "exact_nm"]),
            literal(json!("0.01")),
            ProjectPolicySeed,
            seed(),
            rcpl(BacksideManagement),
            LiveAndNewProjectSeed,
            &["ProjectDisplayUnits", "display formatter"],
            Portable,
            "Length precision",
            "Selects display precision without rounding stored design values.",
            &[],
        ),
        descriptor(
            "datum.units.angle_format",
            "units engine",
            "struct {notation:decimal_degrees|dms|radians,precision}",
            ValueSchema::Semantic(SemanticSchema::AngleFormat),
            literal(json!({"notation":"decimal_degrees","precision":0.1})),
            ProjectPolicySeed,
            seed(),
            rcpl(BacksideManagement),
            LiveAndNewProjectSeed,
            &["ProjectDisplayUnits", "angle formatter", "angle parser"],
            Portable,
            "Angles",
            "Selects angle notation and display precision.",
            &[],
        ),
        descriptor(
            "datum.pcb.route_profile",
            "PCB routing",
            "enum {conservative,balanced,high_density}",
            enum_schema(&["conservative", "balanced", "high_density"]),
            literal(json!("conservative")),
            WorkflowDefault,
            usc(true),
            rcpl(FullManagement),
            PrefillOnly,
            &["route proposal"],
            Portable,
            "Default route profile",
            "Pre-fills the route profile while preserving the explicit per-run choice.",
            &[],
        ),
        descriptor(
            "datum.pcb.net_color_application",
            "PCB presentation",
            "enum {none,ratsnest,copper_ratsnest,all}",
            enum_schema(&["none", "ratsnest", "copper_ratsnest", "all"]),
            literal(json!("ratsnest")),
            Presentation,
            usc(true),
            rc(),
            Live,
            &["board renderer"],
            Portable,
            "Per-net color application mode",
            "Selects where per-net colors apply on copper and airwires.",
            &[],
        ),
        descriptor(
            "datum.pcb.global_airwire_color",
            "PCB presentation",
            "canonical RGBA color or palette token",
            ValueSchema::Semantic(SemanticSchema::RgbaColor),
            runtime("datum_palette.airwire.v1"),
            Presentation,
            usc(true),
            rc(),
            Live,
            &["airwire renderer"],
            Portable,
            "Global airwire color",
            "Sets the default airwire color beneath net-class and per-net overrides.",
            &[],
        ),
        descriptor(
            "datum.pcb.curved_airwires",
            "PCB presentation",
            "bool",
            ValueSchema::Boolean,
            literal(json!(false)),
            Presentation,
            usc(true),
            rc(),
            Live,
            &["airwire renderer"],
            Portable,
            "Curved airwires",
            "Draws airwires as arcs instead of straight lines.",
            &[],
        ),
        descriptor(
            "datum.pcb.selected_ratsnest_only",
            "PCB presentation",
            "bool",
            ValueSchema::Boolean,
            literal(json!(true)),
            Presentation,
            usc(true),
            rc(),
            Live,
            &["selection renderer", "airwire renderer"],
            Portable,
            "Show selected ratsnest only",
            "Shows only selected-object airwires and dims the remainder.",
            &[],
        ),
    ]
}
